(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Standard Model",
  Authors -> {"N. Christensen", "C. Duhr", "B. Fuks"},
  Version -> "1.4.5",
  Date -> "21. 11. 2012",
  Institutions -> {"Michigan State University", "Universite catholique de Louvain (CP3)", "IPHC Strasbourg / University of Strasbourg"},
  Emails -> {"neil@pa.msu.edu", "claude.duhr@uclouvain.be", "benjamin.fuks@cnrs.in2p3.fr"},
  URLs -> "http://feynrules.phys.ucl.ac.be/view/Main/StandardModel"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[5] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[5] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MH[ ___ ] := MH;


TheLabel[ V[5, {__}] ] := TheLabel[V[5]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] , S[2] , S[2] ] == {{(90*I)*c6, 0}},

C[ S[2] , S[2] , S[2] , S[2] , S[3] , -S[3] ] == {{(18*I)*c6, 0}},

C[ S[2] , S[2] , S[3] , S[3] , -S[3] , -S[3] ] == {{(12*I)*c6, 0}},

C[ S[3] , S[3] , S[3] , -S[3] , -S[3] , -S[3] ] == {{(36*I)*c6, 0}},

C[ S[2] , S[2] , S[2] , S[2] , S[1] , S[1] ] == {{(18*I)*c6, 0}},

C[ S[2] , S[2] , S[3] , -S[3] , S[1] , S[1] ] == {{(6*I)*c6, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] , S[1] , S[1] ] == {{(12*I)*c6, 0}},

C[ S[2] , S[2] , S[1] , S[1] , S[1] , S[1] ] == {{(18*I)*c6, 0}},

C[ S[3] , -S[3] , S[1] , S[1] , S[1] , S[1] ] == {{(18*I)*c6, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(90*I)*c6, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(3*I)*(-2*lam + 3*c6*vev^2), 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{I*(-2*lam + 3*c6*vev^2), 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(2*I)*(-2*lam + 3*c6*vev^2), 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{I*(-2*lam + 9*c6*vev^2), 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{I*(-2*lam + 9*c6*vev^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(3*I)*(-2*lam + 15*c6*vev^2), 0}},

C[ S[2] , S[2] , S[2] , S[2] , S[1] ] == {{(18*I)*c6*vev, 0}},

C[ S[2] , S[2] , S[3] , -S[3] , S[1] ] == {{(6*I)*c6*vev, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] , S[1] ] == {{(12*I)*c6*vev, 0}},

C[ S[2] , S[2] , S[1] , S[1] , S[1] ] == {{(18*I)*c6*vev, 0}},

C[ S[3] , -S[3] , S[1] , S[1] , S[1] ] == {{(18*I)*c6*vev, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(90*I)*c6*vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{I*vev*(-2*lam + 3*c6*vev^2), 0}},

C[ S[3] , -S[3] , S[1] ] == {{I*vev*(-2*lam + 3*c6*vev^2), 0}},

C[ S[1] , S[1] , S[1] ] == {{(3*I)*vev*(-2*lam + 5*c6*vev^2), 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{I*EL, 0}, {(-I)*EL, 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*EL, 0}, {I*EL, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}, {0, 0}},

C[ -S[3] , -U[32] , U[1] ] == {{(EL^2*vev)/(2*SW), 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*EL, 0}, {I*EL, 0}, {0, 0}},

C[ S[2] , -U[32] , U[32] ] == {{-(EL^2*vev)/(4*SW^2), 0}},

C[ S[1] , -U[32] , U[32] ] == {{((-I/4)*EL^2*vev)/SW^2, 0}},

C[ -U[32] , U[32] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{((-I)*CW*EL)/SW, 0}, {((-I)*CW*EL)/SW, 0}, {0, 0}},

C[ -S[3] , -U[32] , U[2] ] == {{(EL^2*(CW - SW)*(CW + SW)*vev)/(4*CW*SW^2), 0}},

C[ -U[32] , U[2] , -V[3] ] == {{(I*CW*EL)/SW, 0}, {(I*CW*EL)/SW, 0}, {0, 0}},

C[ S[3] , -U[31] , U[1] ] == {{-(EL^2*vev)/(2*SW), 0}},

C[ -U[31] , U[1] , V[3] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}, {0, 0}},

C[ S[2] , -U[31] , U[31] ] == {{(EL^2*vev)/(4*SW^2), 0}},

C[ S[1] , -U[31] , U[31] ] == {{((-I/4)*EL^2*vev)/SW^2, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*EL, 0}, {I*EL, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{(I*CW*EL)/SW, 0}, {(I*CW*EL)/SW, 0}, {0, 0}},

C[ S[3] , -U[31] , U[2] ] == {{-(EL^2*(CW - SW)*(CW + SW)*vev)/(4*CW*SW^2), 0}},

C[ -U[31] , U[2] , V[3] ] == {{((-I)*CW*EL)/SW, 0}, {((-I)*CW*EL)/SW, 0}, {0, 0}},

C[ S[3] , -U[2] , U[32] ] == {{(EL^2*(CW^2 + SW^2)*vev)/(4*CW*SW^2), 0}},

C[ -U[2] , U[32] , V[3] ] == {{(I*CW*EL)/SW, 0}, {(I*CW*EL)/SW, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[31] ] == {{-(EL^2*(CW^2 + SW^2)*vev)/(4*CW*SW^2), 0}},

C[ -U[2] , U[31] , -V[3] ] == {{((-I)*CW*EL)/SW, 0}, {((-I)*CW*EL)/SW, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(CW^2 + SW^2)^2*vev)/(CW^2*SW^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[5, {e3x2}] ] == {{GS*SUNF[e3x2, e1x1, e2x1], 0}, {GS*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[3] ] == {{IndexDelta[e1x3, e2x3]*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}], 0}, {-(IndexDelta[e1x3, e2x3]*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{-((Conjugate[yd[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2]), 0}, {(IndexDelta[e1x3, e2x3]*yd[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{((-I)*Conjugate[yd[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {((-I)*IndexDelta[e1x3, e2x3]*yd[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[3] ] == {{Conjugate[yl[e2x2, e1x2]], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{-(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]), 0}, {yl[e1x2, e2x2]/Sqrt[2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{((-I)*Conjugate[yl[e2x2, e1x2]])/Sqrt[2], 0}, {((-I)*yl[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{(Conjugate[yu[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {-((IndexDelta[e1x3, e2x3]*yu[e1x2, e2x2])/Sqrt[2]), 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{((-I)*Conjugate[yu[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {((-I)*IndexDelta[e1x3, e2x3]*yu[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{IndexDelta[e1x3, e2x3]*IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}], 0}, {-(IndexDelta[e1x3, e2x3]*IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}]), 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/SW, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*SW), 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*SW), 0}},

C[ S[2] , -S[3] , V[3] ] == {{((-I/2)*EL)/SW, 0}, {((I/2)*EL)/SW, 0}},

C[ -S[3] , S[1] , V[3] ] == {{EL/(2*SW), 0}, {-EL/(2*SW), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*EL, 0}, {I*EL, 0}, {I*EL, 0}, {(-I)*EL, 0}, {(-I)*EL, 0}, {I*EL, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/SW, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*SW), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*SW), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((I/2)*EL)/SW, 0}, {((-I/2)*EL)/SW, 0}},

C[ S[3] , S[1] , -V[3] ] == {{EL/(2*SW), 0}, {-EL/(2*SW), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/SW^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/SW^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/SW^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/SW^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{I*EL^2, 0}, {I*EL^2, 0}, {(-2*I)*EL^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{((-I)*CW*EL)/SW, 0}, {(I*CW*EL)/SW, 0}, {(I*CW*EL)/SW, 0}, {((-I)*CW*EL)/SW, 0}, {((-I)*CW*EL)/SW, 0}, {(I*CW*EL)/SW, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{((-I)*EL^2)/SW^2, 0}, {((-I)*EL^2)/SW^2, 0}, {((2*I)*EL^2)/SW^2, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{0, 0}, {-yl[e1x2, e2x2], 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(CW - SW)*(CW + SW))/(CW*SW), 0}},

C[ S[2] , S[1] , V[2] ] == {{(EL*(CW^2 + SW^2))/(2*CW*SW), 0}, {-(EL*(CW^2 + SW^2))/(2*CW*SW), 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(CW - SW)*(CW + SW))/(CW*SW), 0}, {((-I/2)*EL*(CW - SW)*(CW + SW))/(CW*SW), 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/CW, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*CW), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*CW), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/CW, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*CW), 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*CW), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{((-2*I)*CW*EL^2)/SW, 0}, {(I*CW*EL^2)/SW, 0}, {(I*CW*EL^2)/SW, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(CW^2 + SW^2)^2)/(CW^2*SW^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(CW - SW)^2*(CW + SW)^2)/(CW^2*SW^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(CW^2 + SW^2)^2)/(CW^2*SW^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(CW^2 + SW^2)^2*vev)/(CW^2*SW^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(I*CW^2*EL^2)/SW^2, 0}, {(I*CW^2*EL^2)/SW^2, 0}, {((-2*I)*CW^2*EL^2)/SW^2, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*SW), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{((I/2)*EL*(CW^2 + SW^2)*IndexDelta[e1x2, e2x2])/(CW*SW), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{(-I)*EL*IndexDelta[e1x2, e2x2], 0}, {(-I)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*SW), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{((-I/2)*EL*(CW - SW)*(CW + SW)*IndexDelta[e1x2, e2x2])/(CW*SW), 0}, {(I*EL*SW*IndexDelta[e1x2, e2x2])/CW, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{((2*I)/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {((2*I)/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{(I*EL*CKM[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*SW), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{((I/6)*EL*(3*CW^2 - SW^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(CW*SW), 0}, {(((-2*I)/3)*EL*SW*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/CW, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{(-I/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {(-I/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{(I*EL*Conjugate[CKM[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*SW), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{((-I/6)*EL*(3*CW^2 + SW^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(CW*SW), 0}, {((I/3)*EL*SW*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/CW, 0}}

}

