q(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFTsim_A",
  Authors -> {"I. Brivio, Y. Jiang, M. Trott"},
  Version -> "1.0",
  Date -> "20. 09. 2017",
  Institutions -> {"NBIA and Discovery Center, Niels Bohr Institute, University of Copenhagen"},
  Emails -> {"ilaria.brivio@nbi.ku.dk", "yunjiang@nbi.ku.dk", "michael.trott@cern.ch"},
  References -> "arXiv:1709.06492",
  URLs -> "https://feynrules.irmp.ucl.ac.be/wiki/SMEFT"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MH[ ___ ] := MH;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(6*I)*lam*(Sqrt[2]*dGf + dMH2/MH^2 + (-LambdaSMEFT^2 + (-4*cHbox + cHD)*vevhat^2)/LambdaSMEFT^2), 0}},

C[ S[1] , S[1] , S[1] ] == {{((3*I)/2)*lam*vevhat*(2*Sqrt[2]*dGf + (4*dMH2)/MH^2 + (-4*LambdaSMEFT^2 + 3*(-4*cHbox + cHD)*vevhat^2)/LambdaSMEFT^2), 0}},

C[ S[1] , V[1] , V[1] ] == {{((4*I)*(gHaa*LambdaSMEFT^2 + (cHB*cth^2 + sth*(-(cHWB*cth) + cHW*sth))*vevhat^2))/(LambdaSMEFT^2*vevhat), 0}, {((-4*I)*(gHaa*LambdaSMEFT^2 + (cHB*cth^2 + sth*(-(cHWB*cth) + cHW*sth))*vevhat^2))/(LambdaSMEFT^2*vevhat), 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{((4*I)*(cHB*cth^2 + sth*(-(cHWB*cth) + cHW*sth)))/LambdaSMEFT^2, 0}, {((-4*I)*(cHB*cth^2 + sth*(-(cHWB*cth) + cHW*sth)))/LambdaSMEFT^2, 0}, {0, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{((4*I)*(gHgg + (cHG*vevhat^2)/LambdaSMEFT^2)*IndexDelta[e1x2, e2x2])/vevhat, 0}, {((-4*I)*(gHgg + (cHG*vevhat^2)/LambdaSMEFT^2)*IndexDelta[e1x2, e2x2])/vevhat, 0}, {0, 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{((4*I)*cHG*IndexDelta[e1x2, e2x2])/LambdaSMEFT^2, 0}, {((-4*I)*cHG*IndexDelta[e1x2, e2x2])/LambdaSMEFT^2, 0}, {0, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((4*I)*cHW)/LambdaSMEFT^2, 0}, {((-4*I)*cHW)/LambdaSMEFT^2, 0}, {((I/4)*EL^2*((2 + 4*dgw)*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2))/(LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{((4*I)*cHW*vevhat)/LambdaSMEFT^2, 0}, {((-4*I)*cHW*vevhat)/LambdaSMEFT^2, 0}, {((I/8)*EL^2*vevhat*(2*(2 + Sqrt[2]*dGf + 4*dgw)*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2))/(LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[1] , V[2] ] == {{((2*I)*(gHza*LambdaSMEFT^2 + (2*(-cHB + cHW)*cth*sth + cHWB*(-1 + 2*sth^2))*vevhat^2))/(LambdaSMEFT^2*vevhat), 0}, {((2*I)*(-(gHza*LambdaSMEFT^2) + (cHWB + 2*(cHB - cHW)*cth*sth - 2*cHWB*sth^2)*vevhat^2))/(LambdaSMEFT^2*vevhat), 0}, {((I/4)*EL^2*vevhat*(dsth2*LambdaSMEFT^2 + sth*(2*(-dg1 + dgw)*LambdaSMEFT^2*sth + 2*(dg1 - dgw)*LambdaSMEFT^2*sth^3 - cHWB*cth*vevhat^2 + 2*cHWB*cth*sth^2*vevhat^2)))/(cth^3*LambdaSMEFT^2*sth^3), 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{((-2*I)*(cHWB + 2*(cHB - cHW)*cth*sth - 2*cHWB*sth^2))/LambdaSMEFT^2, 0}, {((2*I)*(cHWB + 2*(cHB - cHW)*cth*sth - 2*cHWB*sth^2))/LambdaSMEFT^2, 0}, {((I/4)*EL^2*(dsth2*LambdaSMEFT^2 + sth*(2*(-dg1 + dgw)*LambdaSMEFT^2*sth + 2*(dg1 - dgw)*LambdaSMEFT^2*sth^3 - cHWB*cth*vevhat^2 + 2*cHWB*cth*sth^2*vevhat^2)))/(cth^3*LambdaSMEFT^2*sth^3), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((4*I)*(cHW*cth^2 + sth*(cHWB*cth + cHB*sth)))/LambdaSMEFT^2, 0}, {((-4*I)*(cHW*cth^2 + sth*(cHWB*cth + cHB*sth)))/LambdaSMEFT^2, 0}, {((-I/4)*EL^2*(2*LambdaSMEFT^2*(-1 - 2*dg1*sth^2 + 2*dgw*(-1 + sth^2)) + (-4*cHbox + cHD - 4*cHWB*cth*sth)*vevhat^2))/(cth^2*LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((4*I)*(cHW*cth^2 + sth*(cHWB*cth + cHB*sth))*vevhat)/LambdaSMEFT^2, 0}, {((-4*I)*(cHW*cth^2 + sth*(cHWB*cth + cHB*sth))*vevhat)/LambdaSMEFT^2, 0}, {((I/8)*EL^2*vevhat*(2*LambdaSMEFT^2*(2 + Sqrt[2]*dGf + 4*dgw + 4*(dg1 - dgw)*sth^2) + (4*cHbox - cHD + 8*cHWB*cth*sth)*vevhat^2))/(cth^2*LambdaSMEFT^2*sth^2), 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e3x2, e1x1, e2x1]), 0}, {-(GS*SUNF[e3x2, e1x1, e2x1]), 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{(4*cHG*GS*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(-4*cHG*GS*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(-4*cHG*GS*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(4*cHG*GS*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(4*cHG*GS*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(-4*cHG*GS*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{(4*cHG*GS*vevhat*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(-4*cHG*GS*vevhat*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(-4*cHG*GS*vevhat*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(4*cHG*GS*vevhat*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(4*cHG*GS*vevhat*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}, {(-4*cHG*GS*vevhat*SUNF[e1x2, e2x2, e3x2])/LambdaSMEFT^2, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{I*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{((-4*I)*cHG*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/LambdaSMEFT^2, 0}, {((4*I)*cHG*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/LambdaSMEFT^2, 0}, {((4*I)*cHG*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/LambdaSMEFT^2, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{((-4*I)*cHG*GS^2*vevhat*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/LambdaSMEFT^2, 0}, {((4*I)*cHG*GS^2*vevhat*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/LambdaSMEFT^2, 0}, {((4*I)*cHG*GS^2*vevhat*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/LambdaSMEFT^2, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{((-I/4)*(4*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2)*IndexDelta[e1x3, e2x3]*yd0[e1x2, e2x2])/(Sqrt[2]*LambdaSMEFT^2), 0}, {((-I/4)*(4*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2)*Conjugate[yd0[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*LambdaSMEFT^2), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{((-I/4)*(4*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2)*yl0[e1x2, e2x2])/(Sqrt[2]*LambdaSMEFT^2), 0}, {((-I/4)*(4*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2)*Conjugate[yl0[e2x2, e1x2]])/(Sqrt[2]*LambdaSMEFT^2), 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{((-I/4)*(4*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2)*IndexDelta[e1x3, e2x3]*yu0[e1x2, e2x2])/(Sqrt[2]*LambdaSMEFT^2), 0}, {((-I/4)*(4*LambdaSMEFT^2 + (4*cHbox - cHD)*vevhat^2)*Conjugate[yu0[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*LambdaSMEFT^2), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(I/2)*EL*(2 + 2*dgw + dsth2/sth^2 + (cHWB*cth*vevhat^2)/(LambdaSMEFT^2*sth)), 0}, {(I/2)*EL*(-2 - 2*dgw - dsth2/sth^2 + (cHWB*cth*vevhat^2)/(LambdaSMEFT^2*sth)), 0}, {(-I/2)*EL*(2 + 2*dgw + dsth2/sth^2 + (cHWB*cth*vevhat^2)/(LambdaSMEFT^2*sth)), 0}, {(-I/2)*EL*(-2 - 2*dgw - dsth2/sth^2 + (cHWB*cth*vevhat^2)/(LambdaSMEFT^2*sth)), 0}, {(-I/2)*EL*(-2 - 2*dgw - dsth2/sth^2 + (cHWB*cth*vevhat^2)/(LambdaSMEFT^2*sth)), 0}, {(I/2)*EL*(-2 - 2*dgw - dsth2/sth^2 + (cHWB*cth*vevhat^2)/(LambdaSMEFT^2*sth)), 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{((2*I)*EL*(cHWB*cth - 2*cHW*sth))/(LambdaSMEFT^2*sth), 0}, {((4*I)*cHW*EL)/LambdaSMEFT^2, 0}, {((2*I)*EL*(-(cHWB*cth) + 2*cHW*sth))/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*EL)/LambdaSMEFT^2, 0}, {((-4*I)*cHW*EL)/LambdaSMEFT^2, 0}, {((4*I)*cHW*EL)/LambdaSMEFT^2, 0}},

C[ S[1] , V[1] , V[3] , -V[3] ] == {{((2*I)*EL*(cHWB*cth - 2*cHW*sth)*vevhat)/(LambdaSMEFT^2*sth), 0}, {((4*I)*cHW*EL*vevhat)/LambdaSMEFT^2, 0}, {((2*I)*EL*(-(cHWB*cth) + 2*cHW*sth)*vevhat)/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*EL*vevhat)/LambdaSMEFT^2, 0}, {((-4*I)*cHW*EL*vevhat)/LambdaSMEFT^2, 0}, {((4*I)*cHW*EL*vevhat)/LambdaSMEFT^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(I*EL^2*(dsth2*LambdaSMEFT^2 + sth*((1 + 2*dgw)*LambdaSMEFT^2*sth - cHWB*cth*vevhat^2)))/(LambdaSMEFT^2*sth^2), 0}, {(I*EL^2*(dsth2*LambdaSMEFT^2 + sth*((1 + 2*dgw)*LambdaSMEFT^2*sth - cHWB*cth*vevhat^2)))/(LambdaSMEFT^2*sth^2), 0}, {((-2*I)*EL^2*(dsth2*LambdaSMEFT^2 + sth*((1 + 2*dgw)*LambdaSMEFT^2*sth - cHWB*cth*vevhat^2)))/(LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{((-4*I)*cHW*EL^2)/LambdaSMEFT^2, 0}, {((-4*I)*cHW*EL^2)/LambdaSMEFT^2, 0}, {((8*I)*cHW*EL^2)/LambdaSMEFT^2, 0}},

C[ S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{((-4*I)*cHW*EL^2*vevhat)/LambdaSMEFT^2, 0}, {((-4*I)*cHW*EL^2*vevhat)/LambdaSMEFT^2, 0}, {((8*I)*cHW*EL^2*vevhat)/LambdaSMEFT^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{((-4*I)*cHW*cth*EL)/(LambdaSMEFT^2*sth), 0}, {((4*I)*cHW*cth*EL)/(LambdaSMEFT^2*sth), 0}, {((4*I)*cHW*cth*EL)/(LambdaSMEFT^2*sth), 0}, {((-2*I)*EL*(2*cHW*cth + cHWB*sth))/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*cth*EL)/(LambdaSMEFT^2*sth), 0}, {((2*I)*EL*(2*cHW*cth + cHWB*sth))/(LambdaSMEFT^2*sth), 0}},

C[ V[3] , -V[3] , V[2] ] == {{((-I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dgw + dsth2 + 2*(1 + dgw)*sth^2) - cHWB*cth*sth*vevhat^2))/(cth*LambdaSMEFT^2*sth), 0}, {((I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dgw + dsth2 + 2*(1 + dgw)*sth^2) - cHWB*cth*sth*vevhat^2))/(cth*LambdaSMEFT^2*sth), 0}, {((I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dgw + dsth2 + 2*(1 + dgw)*sth^2) - cHWB*cth*sth*vevhat^2))/(cth*LambdaSMEFT^2*sth), 0}, {((-I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dgw + dsth2 + 2*(1 + dgw)*sth^2) + cHWB*cth*sth*vevhat^2))/(cth*LambdaSMEFT^2*sth), 0}, {((-I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dgw + dsth2 + 2*(1 + dgw)*sth^2) - cHWB*cth*sth*vevhat^2))/(cth*LambdaSMEFT^2*sth), 0}, {((I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dgw + dsth2 + 2*(1 + dgw)*sth^2) + cHWB*cth*sth*vevhat^2))/(cth*LambdaSMEFT^2*sth), 0}},

C[ S[1] , V[3] , -V[3] , V[2] ] == {{((-4*I)*cHW*cth*EL*vevhat)/(LambdaSMEFT^2*sth), 0}, {((4*I)*cHW*cth*EL*vevhat)/(LambdaSMEFT^2*sth), 0}, {((4*I)*cHW*cth*EL*vevhat)/(LambdaSMEFT^2*sth), 0}, {((-2*I)*EL*(2*cHW*cth + cHWB*sth)*vevhat)/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*cth*EL*vevhat)/(LambdaSMEFT^2*sth), 0}, {((2*I)*EL*(2*cHW*cth + cHWB*sth)*vevhat)/(LambdaSMEFT^2*sth), 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{((-I)*(1 + 2*dgw)*EL^2)/sth^2, 0}, {((-I)*(1 + 2*dgw)*EL^2)/sth^2, 0}, {((2*I)*(1 + 2*dgw)*EL^2)/sth^2, 0}},

C[ S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{((4*I)*cHW*EL^2)/(LambdaSMEFT^2*sth^2), 0}, {((4*I)*cHW*EL^2)/(LambdaSMEFT^2*sth^2), 0}, {((-8*I)*cHW*EL^2)/(LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{((4*I)*cHW*EL^2*vevhat)/(LambdaSMEFT^2*sth^2), 0}, {((4*I)*cHW*EL^2*vevhat)/(LambdaSMEFT^2*sth^2), 0}, {((-8*I)*cHW*EL^2*vevhat)/(LambdaSMEFT^2*sth^2), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(I*EL^2*(dsth2*LambdaSMEFT^2*(-1 + 2*sth^2) + sth*(2*(1 + 2*dgw)*LambdaSMEFT^2*sth*(-1 + sth^2) + cHWB*cth*(1 - 2*sth^2)*vevhat^2)))/(cth*LambdaSMEFT^2*sth^3), 0}, {((-I/2)*EL^2*(dsth2*LambdaSMEFT^2*(-1 + 2*sth^2) + sth*(2*(1 + 2*dgw)*LambdaSMEFT^2*sth*(-1 + sth^2) + cHWB*cth*(1 - 2*sth^2)*vevhat^2)))/(cth*LambdaSMEFT^2*sth^3), 0}, {((-I/2)*EL^2*(dsth2*LambdaSMEFT^2*(-1 + 2*sth^2) + sth*(2*(1 + 2*dgw)*LambdaSMEFT^2*sth*(-1 + sth^2) + cHWB*cth*(1 - 2*sth^2)*vevhat^2)))/(cth*LambdaSMEFT^2*sth^3), 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{((8*I)*cHW*cth*EL^2)/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*cth*EL^2)/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*cth*EL^2)/(LambdaSMEFT^2*sth), 0}},

C[ S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{((8*I)*cHW*cth*EL^2*vevhat)/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*cth*EL^2*vevhat)/(LambdaSMEFT^2*sth), 0}, {((-4*I)*cHW*cth*EL^2*vevhat)/(LambdaSMEFT^2*sth), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{((-I)*EL^2*(LambdaSMEFT^2*(-1 + dsth2 + sth^2 + 2*dgw*(-1 + sth^2)) - cHWB*cth*sth*vevhat^2))/(LambdaSMEFT^2*sth^2), 0}, {((-I)*EL^2*(LambdaSMEFT^2*(-1 + dsth2 + sth^2 + 2*dgw*(-1 + sth^2)) - cHWB*cth*sth*vevhat^2))/(LambdaSMEFT^2*sth^2), 0}, {((2*I)*EL^2*(LambdaSMEFT^2*(-1 + dsth2 + sth^2 + 2*dgw*(-1 + sth^2)) - cHWB*cth*sth*vevhat^2))/(LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{((-4*I)*cHW*cth^2*EL^2)/(LambdaSMEFT^2*sth^2), 0}, {((-4*I)*cHW*cth^2*EL^2)/(LambdaSMEFT^2*sth^2), 0}, {((8*I)*cHW*cth^2*EL^2)/(LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{((-4*I)*cHW*cth^2*EL^2*vevhat)/(LambdaSMEFT^2*sth^2), 0}, {((-4*I)*cHW*cth^2*EL^2*vevhat)/(LambdaSMEFT^2*sth^2), 0}, {((8*I)*cHW*cth^2*EL^2*vevhat)/(LambdaSMEFT^2*sth^2), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{((-I/12)*EL*(dsth2*LambdaSMEFT^2*(-3 + 2*sth^2) + sth*(-2*(-2 + dg1 - 3*dgw)*LambdaSMEFT^2*sth*(-1 + sth^2) + cHWB*cth*(3 - 4*sth^2)*vevhat^2))*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth^2*LambdaSMEFT^2*sth^2), 0}, {((-I/6)*EL*(LambdaSMEFT^2*(-2 - 2*dg1 + dsth2 + 2*(1 + dg1)*sth^2) + cHWB*cth*sth*vevhat^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth^2*LambdaSMEFT^2), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{((-I/4)*EL*(dsth2*LambdaSMEFT^2*(-1 + 2*sth^2) + sth*(2*(2 + dg1 + dgw)*LambdaSMEFT^2*sth*(-1 + sth^2) + cHWB*cth*vevhat^2))*IndexDelta[e1x2, e2x2])/(cth^2*LambdaSMEFT^2*sth^2), 0}, {((-I/2)*EL*(LambdaSMEFT^2*(-2 - 2*dg1 + dsth2 + 2*(1 + dg1)*sth^2) + cHWB*cth*sth*vevhat^2)*IndexDelta[e1x2, e2x2])/(cth^2*LambdaSMEFT^2), 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{((I/12)*EL*(dsth2*LambdaSMEFT^2*(-3 + 4*sth^2) + sth*(2*(4 + dg1 + 3*dgw)*LambdaSMEFT^2*sth*(-1 + sth^2) + cHWB*cth*(3 - 2*sth^2)*vevhat^2))*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth^2*LambdaSMEFT^2*sth^2), 0}, {((I/3)*EL*(LambdaSMEFT^2*(-2 - 2*dg1 + dsth2 + 2*(1 + dg1)*sth^2) + cHWB*cth*sth*vevhat^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth^2*LambdaSMEFT^2), 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[1] ] == {{((-I/4)*EL*(dsth2*LambdaSMEFT^2 + sth*(2*(-dg1 + dgw)*LambdaSMEFT^2*sth + 2*(dg1 - dgw)*LambdaSMEFT^2*sth^3 - cHWB*cth*vevhat^2 + 2*cHWB*cth*sth^2*vevhat^2))*IndexDelta[e1x2, e2x2])/(cth^2*LambdaSMEFT^2*sth^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{(-I)*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {(-I)*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{(-I)*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {(-I)*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{((-I)*(1 + dgw)*EL*CKM[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*sth), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{((-I)*(1 + dgw)*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sth), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{((-I)*(1 + dgw)*EL*Conjugate[CKM[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*sth), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{((-I)*(1 + dgw)*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sth), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{((-I/6)*EL*(LambdaSMEFT^2*(-3 - 3*dgw + dsth2 + (2 - dg1 + 3*dgw)*sth^2) - 2*cHWB*cth*sth*vevhat^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth*LambdaSMEFT^2*sth), 0}, {((-I/6)*EL*(dsth2*LambdaSMEFT^2 + sth*(2*(1 + dg1)*LambdaSMEFT^2*sth + cHWB*cth*vevhat^2))*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth*LambdaSMEFT^2*sth), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{((-I/2)*EL*(-1 - dgw + dsth2 + (2 + dg1 + dgw)*sth^2)*IndexDelta[e1x2, e2x2])/(cth*sth), 0}, {((-I/2)*EL*(dsth2*LambdaSMEFT^2 + sth*(2*(1 + dg1)*LambdaSMEFT^2*sth + cHWB*cth*vevhat^2))*IndexDelta[e1x2, e2x2])/(cth*LambdaSMEFT^2*sth), 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{((I/6)*EL*(LambdaSMEFT^2*(-3 - 3*dgw + 2*dsth2 + (4 + dg1 + 3*dgw)*sth^2) - cHWB*cth*sth*vevhat^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth*LambdaSMEFT^2*sth), 0}, {((I/3)*EL*(dsth2*LambdaSMEFT^2 + sth*(2*(1 + dg1)*LambdaSMEFT^2*sth + cHWB*cth*vevhat^2))*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cth*LambdaSMEFT^2*sth), 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{((-I/2)*EL*(LambdaSMEFT^2*(1 + dgw + (dg1 - dgw)*sth^2) + cHWB*cth*sth*vevhat^2)*IndexDelta[e1x2, e2x2])/(cth*LambdaSMEFT^2*sth), 0}, {0, 0}}

}

