(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"D6",
  Authors -> {"M. Fedele"},
  Date -> "15/02/2016",
  Institutions -> {"INFN RM1"},
  Emails -> {"marco.fedele@uniroma1.it"},
  Version -> "1.0"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}};

FR$GoldstoneList={S[2], S[20], S[3], S[30]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

V[1] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    InsertOnly -> Loop,
    Mass -> 0 },

V[10] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> ComposedChar["\\gamma", Null, Null, "\\hat"],
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    InsertOnly -> {Internal, External},
    Mass -> 0 },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    InsertOnly -> Loop,
    Mass -> MZ,
    Indices -> {} },

V[20] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["Z", Null, Null, "\\hat"],
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    InsertOnly -> {Internal, External},
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    InsertOnly -> Loop,
    Mass -> MW,
    Indices -> {} },

V[30] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> ComposedChar["W", Null, Null, "\\hat"],
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    InsertOnly -> {Internal, External},
    Mass -> MW,
    Indices -> {} },

V[5] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uA,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[5] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uG,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    InsertOnly -> Loop,
    Mass -> MH,
    Indices -> {} },

S[10] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["H", Null, Null, "\\hat"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    InsertOnly -> {Internal, External},
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    InsertOnly -> Loop,
    Mass -> MZ,
    Indices -> {} },

S[20] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["G", Null, "0", "\\hat"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    InsertOnly -> {Internal, External},
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    InsertOnly -> Loop,
    Mass -> MW,
    Indices -> {} },

S[30] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> ComposedChar["G", Null, Null, "\\hat"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    InsertOnly -> {Internal, External},
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[Q];
GaugeXi[ V[10] ] = GaugeXi[bg];
GaugeXi[ V[2] ] = GaugeXi[Q];
GaugeXi[ V[3] ] = GaugeXi[Q];
GaugeXi[ V[30] ] = GaugeXi[bg];
GaugeXi[ V[5] ] = GaugeXi[Q];
GaugeXi[ U[1] ] = GaugeXi[Q];
GaugeXi[ U[2] ] = GaugeXi[Q];
GaugeXi[ U[31] ] = GaugeXi[Q];
GaugeXi[ U[32] ] = GaugeXi[Q];
GaugeXi[ U[5] ] = GaugeXi[Q];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[10] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Q];
GaugeXi[ S[20] ] = GaugeXi[bg];
GaugeXi[ S[3] ] = GaugeXi[Q];
GaugeXi[ S[30] ] = GaugeXi[bg];

Ml[ 1 ] := 0;
Ml[ 2 ] := 0;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MH[ ___ ] := MH;


TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "m";
TheLabel[ F[2, {3}] ] := "tt";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ V[5, {__}] ] := TheLabel[V[5]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}},

C[ V[10] , V[3] , -V[3] ] == {{(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}},

C[ V[1] , V[3] , -V[30] ] == {{(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}},

C[ V[10] , V[3] , -V[30] ] == {{(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}},

C[ V[1] , -V[3] , V[30] ] == {{I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}},

C[ V[10] , -V[3] , V[30] ] == {{I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[1] , V[10] , V[3] , -V[3] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[10] , V[10] , V[3] , -V[3] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}},

C[ V[3] , -V[3] , V[20] ] == {{(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}},

C[ V[1] , V[30] , -V[30] ] == {{(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}},

C[ V[10] , V[30] , -V[30] ] == {{(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {(-I)*BBBB*gw*sw, 0}, {I*BBBB*gw*sw, 0}},

C[ V[1] , V[1] , -V[3] , V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[1] , V[10] , -V[3] , V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[10] , V[10] , -V[3] , V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ -V[3] , V[30] , V[2] ] == {{I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}},

C[ -V[3] , V[30] , V[20] ] == {{I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}},

C[ V[3] , -V[3] , -V[3] , V[30] ] == {{(2*I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}},

C[ -V[3] , -V[3] , V[30] , V[30] ] == {{(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[1] , V[10] , V[3] , -V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[10] , V[10] , V[3] , -V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[3] , -V[30] , V[2] ] == {{(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}},

C[ V[3] , -V[30] , V[20] ] == {{(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}},

C[ V[3] , V[3] , -V[3] , -V[30] ] == {{(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}},

C[ V[1] , V[1] , V[30] , -V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[1] , V[10] , V[30] , -V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[10] , V[10] , V[30] , -V[30] ] == {{I*BBBB*gw^2*sw^2, 0}, {I*BBBB*gw^2*sw^2, 0}, {(-2*I)*BBBB*gw^2*sw^2, 0}},

C[ V[3] , -V[3] , V[30] , -V[30] ] == {{(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}},

C[ V[30] , -V[30] , V[2] ] == {{(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}},

C[ V[30] , -V[30] , V[20] ] == {{(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {(-I)*BBBB*cw*gw, 0}, {I*BBBB*cw*gw, 0}},

C[ -V[3] , V[30] , V[30] , -V[30] ] == {{(2*I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}},

C[ V[3] , V[3] , -V[30] , -V[30] ] == {{(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}},

C[ V[3] , V[30] , -V[30] , -V[30] ] == {{(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}},

C[ V[30] , V[30] , -V[30] , -V[30] ] == {{(-I)*BBBB*gw^2, 0}, {(-I)*BBBB*gw^2, 0}, {(2*I)*BBBB*gw^2, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , V[3] , -V[3] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[1] , -V[3] , V[30] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , -V[3] , V[30] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[1] , V[3] , -V[30] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , V[3] , -V[30] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[1] , V[30] , -V[30] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , V[30] , -V[30] , V[2] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ -V[3] , V[30] , V[2] , V[2] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[3] , -V[30] , V[2] , V[2] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[30] , -V[30] , V[2] , V[2] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[1] , V[3] , -V[3] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , V[3] , -V[3] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[1] , -V[3] , V[30] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , -V[3] , V[30] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[1] , V[3] , -V[30] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , V[3] , -V[30] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[1] , V[30] , -V[30] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[10] , V[30] , -V[30] , V[20] ] == {{(-2*I)*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}, {I*BBBB*cw*gw^2*sw, 0}},

C[ V[3] , -V[3] , V[2] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ -V[3] , V[30] , V[2] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[3] , -V[30] , V[2] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[30] , -V[30] , V[2] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[3] , -V[3] , V[20] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ -V[3] , V[30] , V[20] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[3] , -V[30] , V[20] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}},

C[ V[30] , -V[30] , V[20] , V[20] ] == {{I*BBBB*cw^2*gw^2, 0}, {I*BBBB*cw^2*gw^2, 0}, {(-2*I)*BBBB*cw^2*gw^2, 0}}

}

