(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"D6",
  Authors -> {"M. Fedele"},
  Date -> "15/02/2016",
  Institutions -> {"INFN RM1"},
  Emails -> {"marco.fedele@uniroma1.it"},
  Version -> "1.0"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

V[1] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[5] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uA,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[5] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uG,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[5] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

Ml[ 1 ] := 0;
Ml[ 2 ] := 0;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MH[ ___ ] := MH;


TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "m";
TheLabel[ F[2, {3}] ] := "tt";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ V[5, {__}] ] := TheLabel[V[5]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , V[1] , V[1] ] == {{((4*I)*(cB*cw^2 + sw*(-(cw*cWB) + cW*sw)))/LAMBDA^2, 0}, {((-4*I)*(cB*cw^2 + sw*(-(cw*cWB) + cW*sw)))/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{((4*I)*(cB*cw^2 + sw*(cw*cWB + cW*sw)))/LAMBDA^2, 0}, {((-4*I)*(cB*cw^2 + sw*(cw*cWB + cW*sw)))/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{((4*I)*(cB*cw^2 + sw*(-(cw*cWB) + cW*sw)))/LAMBDA^2, 0}, {((-4*I)*(cB*cw^2 + sw*(-(cw*cWB) + cW*sw)))/LAMBDA^2, 0}},

C[ S[1] , V[1] , V[1] ] == {{((4*I)*(cB*cw^2 + sw*(-(cw*cWB) + cW*sw))*vev)/LAMBDA^2, 0}, {((-4*I)*(cB*cw^2 + sw*(-(cw*cWB) + cW*sw))*vev)/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((2*I)*cw*cWB)/LAMBDA^2, 0}, {((-2*I)*cw*cWB)/LAMBDA^2, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{(2*cw*cWB)/LAMBDA^2, 0}, {(-2*cw*cWB)/LAMBDA^2, 0}},

C[ -S[3] , V[1] , V[3] ] == {{(2*cw*cWB*vev)/LAMBDA^2, 0}, {(-2*cw*cWB*vev)/LAMBDA^2, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((2*I)*cw*cWB)/LAMBDA^2, 0}, {((-2*I)*cw*cWB)/LAMBDA^2, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{(-2*cw*cWB)/LAMBDA^2, 0}, {(2*cw*cWB)/LAMBDA^2, 0}},

C[ S[3] , V[1] , -V[3] ] == {{(-2*cw*cWB*vev)/LAMBDA^2, 0}, {(2*cw*cWB*vev)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((4*I)*cW)/LAMBDA^2, 0}, {((-4*I)*cW)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((4*I)*cW)/LAMBDA^2, 0}, {((-4*I)*cW)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((4*I)*cW)/LAMBDA^2, 0}, {((-4*I)*cW)/LAMBDA^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((4*I)*cW*vev)/LAMBDA^2, 0}, {((-4*I)*cW*vev)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[1] , V[2] ] == {{((-2*I)*(cw^2*cWB + 2*cw*(cB - cW)*sw - cWB*sw^2))/LAMBDA^2, 0}, {((2*I)*(cw^2*cWB + 2*cw*(cB - cW)*sw - cWB*sw^2))/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{((2*I)*(cw^2*cWB + 2*cw*(-cB + cW)*sw - cWB*sw^2))/LAMBDA^2, 0}, {((2*I)*(-(cw^2*cWB) + 2*cw*(cB - cW)*sw + cWB*sw^2))/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{((-2*I)*(cw^2*cWB + 2*cw*(cB - cW)*sw - cWB*sw^2))/LAMBDA^2, 0}, {((2*I)*(cw^2*cWB + 2*cw*(cB - cW)*sw - cWB*sw^2))/LAMBDA^2, 0}},

C[ S[1] , V[1] , V[2] ] == {{((-2*I)*(cw^2*cWB + 2*cw*(cB - cW)*sw - cWB*sw^2)*vev)/LAMBDA^2, 0}, {((2*I)*(cw^2*cWB + 2*cw*(cB - cW)*sw - cWB*sw^2)*vev)/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((-2*I)*cWB*sw)/LAMBDA^2, 0}, {((2*I)*cWB*sw)/LAMBDA^2, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{(-2*cWB*sw)/LAMBDA^2, 0}, {(2*cWB*sw)/LAMBDA^2, 0}},

C[ -S[3] , V[3] , V[2] ] == {{(-2*cWB*sw*vev)/LAMBDA^2, 0}, {(2*cWB*sw*vev)/LAMBDA^2, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((-2*I)*cWB*sw)/LAMBDA^2, 0}, {((2*I)*cWB*sw)/LAMBDA^2, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{(2*cWB*sw)/LAMBDA^2, 0}, {(-2*cWB*sw)/LAMBDA^2, 0}},

C[ S[3] , -V[3] , V[2] ] == {{(2*cWB*sw*vev)/LAMBDA^2, 0}, {(-2*cWB*sw*vev)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((4*I)*(cw^2*cW + cw*cWB*sw + cB*sw^2))/LAMBDA^2, 0}, {((-4*I)*(cw^2*cW + cw*cWB*sw + cB*sw^2))/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((4*I)*(cw^2*cW - cw*cWB*sw + cB*sw^2))/LAMBDA^2, 0}, {((-4*I)*(cw^2*cW - cw*cWB*sw + cB*sw^2))/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((4*I)*(cw^2*cW + cw*cWB*sw + cB*sw^2))/LAMBDA^2, 0}, {((-4*I)*(cw^2*cW + cw*cWB*sw + cB*sw^2))/LAMBDA^2, 0}},

C[ S[1] , V[2] , V[2] ] == {{((4*I)*(cw^2*cW + cw*cWB*sw + cB*sw^2)*vev)/LAMBDA^2, 0}, {((-4*I)*(cw^2*cW + cw*cWB*sw + cB*sw^2)*vev)/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[1] , V[1] , V[3] ] == {{((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {0, 0}},

C[ -S[3] , S[1] , V[1] , V[1] , V[3] ] == {{(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {0, 0}},

C[ -S[3] , V[1] , V[1] , V[3] ] == {{(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , V[1] , V[3] , -V[3] ] == {{((2*I)*gw*(cw*cWB - 2*cW*sw))/LAMBDA^2, 0}, {((4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((-2*I)*gw*(cw*cWB - 2*cW*sw))/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((4*I)*cW*gw*sw)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[1] , V[3] , -V[3] ] == {{((-2*I)*gw*(cw*cWB + 2*cW*sw))/LAMBDA^2, 0}, {((4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((2*I)*gw*(cw*cWB + 2*cW*sw))/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((4*I)*cW*gw*sw)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{((2*I)*gw*(cw*cWB - 2*cW*sw))/LAMBDA^2, 0}, {((4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((-2*I)*gw*(cw*cWB - 2*cW*sw))/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw)/LAMBDA^2, 0}, {((4*I)*cW*gw*sw)/LAMBDA^2, 0}},

C[ S[1] , V[1] , V[3] , -V[3] ] == {{((2*I)*gw*(cw*cWB - 2*cW*sw)*vev)/LAMBDA^2, 0}, {((4*I)*cW*gw*sw*vev)/LAMBDA^2, 0}, {((-2*I)*gw*(cw*cWB - 2*cW*sw)*vev)/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw*vev)/LAMBDA^2, 0}, {((-4*I)*cW*gw*sw*vev)/LAMBDA^2, 0}, {((4*I)*cW*gw*sw*vev)/LAMBDA^2, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(I*gw*(cw*cWB - 2*cW*sw)*vev^2)/LAMBDA^2, 0}, {((2*I)*cW*gw*sw*vev^2)/LAMBDA^2, 0}, {((-I)*gw*(cw*cWB - 2*cW*sw)*vev^2)/LAMBDA^2, 0}, {((-2*I)*cW*gw*sw*vev^2)/LAMBDA^2, 0}, {((-2*I)*cW*gw*sw*vev^2)/LAMBDA^2, 0}, {((2*I)*cW*gw*sw*vev^2)/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[1] , V[3] , V[2] ] == {{((2*I)*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {((-2*I)*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {((2*I)*cWB*gw*sw^2)/LAMBDA^2, 0}, {((-2*I)*cWB*gw*sw^2)/LAMBDA^2, 0}},

C[ -S[3] , S[1] , V[1] , V[3] , V[2] ] == {{(2*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {(-2*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {(2*cWB*gw*sw^2)/LAMBDA^2, 0}, {(-2*cWB*gw*sw^2)/LAMBDA^2, 0}},

C[ -S[3] , V[1] , V[3] , V[2] ] == {{(2*cw^2*cWB*gw*vev)/LAMBDA^2, 0}, {0, 0}, {(-2*cw^2*cWB*gw*vev)/LAMBDA^2, 0}, {0, 0}, {(2*cWB*gw*sw^2*vev)/LAMBDA^2, 0}, {(-2*cWB*gw*sw^2*vev)/LAMBDA^2, 0}},

C[ S[2] , S[3] , V[1] , V[1] , -V[3] ] == {{((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[1] , V[1] , V[1] , -V[3] ] == {{(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {0, 0}},

C[ S[3] , V[1] , V[1] , -V[3] ] == {{(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[3] , V[1] , -V[3] , V[2] ] == {{((-2*I)*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {((2*I)*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {((-2*I)*cWB*gw*sw^2)/LAMBDA^2, 0}, {((2*I)*cWB*gw*sw^2)/LAMBDA^2, 0}},

C[ S[3] , S[1] , V[1] , -V[3] , V[2] ] == {{(2*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {(-2*cw^2*cWB*gw)/LAMBDA^2, 0}, {0, 0}, {(2*cWB*gw*sw^2)/LAMBDA^2, 0}, {(-2*cWB*gw*sw^2)/LAMBDA^2, 0}},

C[ S[3] , V[1] , -V[3] , V[2] ] == {{(2*cw^2*cWB*gw*vev)/LAMBDA^2, 0}, {0, 0}, {(-2*cw^2*cWB*gw*vev)/LAMBDA^2, 0}, {0, 0}, {(2*cWB*gw*sw^2*vev)/LAMBDA^2, 0}, {(-2*cWB*gw*sw^2*vev)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[1] , V[1] , V[3] , -V[3] ] == {{((-4*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}, {((-4*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}, {((8*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[1] , V[1] , V[3] , -V[3] ] == {{((-4*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}, {((-4*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}, {((8*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{((-4*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}, {((-4*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}, {((8*I)*cW*gw^2*sw^2)/LAMBDA^2, 0}},

C[ S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{((-4*I)*cW*gw^2*sw^2*vev)/LAMBDA^2, 0}, {((-4*I)*cW*gw^2*sw^2*vev)/LAMBDA^2, 0}, {((8*I)*cW*gw^2*sw^2*vev)/LAMBDA^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{((-2*I)*cW*gw^2*sw^2*vev^2)/LAMBDA^2, 0}, {((-2*I)*cW*gw^2*sw^2*vev^2)/LAMBDA^2, 0}, {((4*I)*cW*gw^2*sw^2*vev^2)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] , V[2] ] == {{((-4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((-2*I)*gw*(2*cw*cW + cWB*sw))/LAMBDA^2, 0}, {((2*I)*gw*(2*cw*cW + cWB*sw))/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] , V[2] ] == {{((-4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((-2*I)*gw*(2*cw*cW - cWB*sw))/LAMBDA^2, 0}, {((2*I)*gw*(2*cw*cW - cWB*sw))/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{((-4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw)/LAMBDA^2, 0}, {((-2*I)*gw*(2*cw*cW + cWB*sw))/LAMBDA^2, 0}, {((2*I)*gw*(2*cw*cW + cWB*sw))/LAMBDA^2, 0}},

C[ S[1] , V[3] , -V[3] , V[2] ] == {{((-4*I)*cw*cW*gw*vev)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw*vev)/LAMBDA^2, 0}, {((4*I)*cw*cW*gw*vev)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw*vev)/LAMBDA^2, 0}, {((-2*I)*gw*(2*cw*cW + cWB*sw)*vev)/LAMBDA^2, 0}, {((2*I)*gw*(2*cw*cW + cWB*sw)*vev)/LAMBDA^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{((-2*I)*cw*cW*gw*vev^2)/LAMBDA^2, 0}, {((2*I)*cw*cW*gw*vev^2)/LAMBDA^2, 0}, {((2*I)*cw*cW*gw*vev^2)/LAMBDA^2, 0}, {((-I)*gw*(2*cw*cW + cWB*sw)*vev^2)/LAMBDA^2, 0}, {((-2*I)*cw*cW*gw*vev^2)/LAMBDA^2, 0}, {(I*gw*(2*cw*cW + cWB*sw)*vev^2)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[3] , V[3] , -V[3] , -V[3] ] == {{((4*I)*cW*gw^2)/LAMBDA^2, 0}, {((4*I)*cW*gw^2)/LAMBDA^2, 0}, {((-8*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , V[3] , -V[3] , -V[3] ] == {{((4*I)*cW*gw^2)/LAMBDA^2, 0}, {((4*I)*cW*gw^2)/LAMBDA^2, 0}, {((-8*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{((4*I)*cW*gw^2)/LAMBDA^2, 0}, {((4*I)*cW*gw^2)/LAMBDA^2, 0}, {((-8*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{((4*I)*cW*gw^2*vev)/LAMBDA^2, 0}, {((4*I)*cW*gw^2*vev)/LAMBDA^2, 0}, {((-8*I)*cW*gw^2*vev)/LAMBDA^2, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{((2*I)*cW*gw^2*vev^2)/LAMBDA^2, 0}, {((2*I)*cW*gw^2*vev^2)/LAMBDA^2, 0}, {((-4*I)*cW*gw^2*vev^2)/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[3] , V[2] , V[2] ] == {{0, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}},

C[ -S[3] , S[1] , V[3] , V[2] , V[2] ] == {{0, 0}, {(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}},

C[ -S[3] , V[3] , V[2] , V[2] ] == {{0, 0}, {(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {0, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[1] , V[3] , -V[3] , V[2] ] == {{((8*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[1] , V[3] , -V[3] , V[2] ] == {{((8*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{((8*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw)/LAMBDA^2, 0}},

C[ S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{((8*I)*cw*cW*gw^2*sw*vev)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw*vev)/LAMBDA^2, 0}, {((-4*I)*cw*cW*gw^2*sw*vev)/LAMBDA^2, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{((4*I)*cw*cW*gw^2*sw*vev^2)/LAMBDA^2, 0}, {((-2*I)*cw*cW*gw^2*sw*vev^2)/LAMBDA^2, 0}, {((-2*I)*cw*cW*gw^2*sw*vev^2)/LAMBDA^2, 0}},

C[ S[2] , S[3] , -V[3] , V[2] , V[2] ] == {{0, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}, {((-2*I)*cw*cWB*gw*sw)/LAMBDA^2, 0}},

C[ S[3] , S[1] , -V[3] , V[2] , V[2] ] == {{0, 0}, {(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {0, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw)/LAMBDA^2, 0}},

C[ S[3] , -V[3] , V[2] , V[2] ] == {{0, 0}, {(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {0, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(-2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}, {(2*cw*cWB*gw*sw*vev)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] , V[2] , V[2] ] == {{((-4*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}, {((-4*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}, {((8*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] , V[2] , V[2] ] == {{((-4*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}, {((-4*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}, {((8*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{((-4*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}, {((-4*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}, {((8*I)*cw^2*cW*gw^2)/LAMBDA^2, 0}},

C[ S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{((-4*I)*cw^2*cW*gw^2*vev)/LAMBDA^2, 0}, {((-4*I)*cw^2*cW*gw^2*vev)/LAMBDA^2, 0}, {((8*I)*cw^2*cW*gw^2*vev)/LAMBDA^2, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{((-2*I)*cw^2*cW*gw^2*vev^2)/LAMBDA^2, 0}, {((-2*I)*cw^2*cW*gw^2*vev^2)/LAMBDA^2, 0}, {((4*I)*cw^2*cW*gw^2*vev^2)/LAMBDA^2, 0}}

}

