(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"D6",
  Authors -> {"M. Fedele"},
  Date -> "15/02/2016",
  Institutions -> {"INFN RM1"},
  Emails -> {"marco.fedele@uniroma1.it"},
  Version -> "1.0"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

V[1] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

V[2] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "W^0",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    InsertOnly -> Loop },

V[20] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "W^0",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0, 
    InsertOnly -> {Internal, External} },

V[3] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> 0 },

V[5] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

V[6] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "B",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0, 
    InsertOnly -> Loop  },

V[60] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "B",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0, 
    InsertOnly -> {Internal, External}  },

U[1] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uA,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[2] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uW0,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[31] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorLabel -> uWp,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[32] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorLabel -> uWm,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uG,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[6] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uB,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {}, 
    InsertOnly -> Loop },

S[10] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {}, 
    InsertOnly -> {Internal, External} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

Ml[ 1 ] := 0;
Ml[ 2 ] := 0;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;


TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "m";
TheLabel[ F[2, {3}] ] := "tt";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ V[5, {__}] ] := TheLabel[V[5]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[3] ] == {{IndexDelta[e1x3, e2x3]*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}], 0}, {-(IndexDelta[e1x3, e2x3]*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{-((Conjugate[yd[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2]), 0}, {(IndexDelta[e1x3, e2x3]*yd[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{((-I)*Conjugate[yd[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {((-I)*IndexDelta[e1x3, e2x3]*yd[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[3] ] == {{Conjugate[yl[e2x2, e1x2]], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{-(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]), 0}, {yl[e1x2, e2x2]/Sqrt[2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{((-I)*Conjugate[yl[e2x2, e1x2]])/Sqrt[2], 0}, {((-I)*yl[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{(Conjugate[yu[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {-((IndexDelta[e1x3, e2x3]*yu[e1x2, e2x2])/Sqrt[2]), 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{((-I)*Conjugate[yu[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {((-I)*IndexDelta[e1x3, e2x3]*yu[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{IndexDelta[e1x3, e2x3]*IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}], 0}, {-(IndexDelta[e1x3, e2x3]*IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}]), 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{0, 0}, {-yl[e1x2, e2x2], 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[3] , V[2] , -V[3] ] == {{I*gw, 0}, {(-I)*gw, 0}, {(-I)*gw, 0}, {I*gw, 0}, {I*gw, 0}, {(-I)*gw, 0}},

C[ V[20] , V[3] , -V[3] ] == {{(-2*I)*gw, 0}, {(-2*I)*gw, 0}, {(-I)*gw, 0}, {I*gw, 0}, {(-2*I)*gw, 0}, {(-2*I)*gw, 0}},

C[ V[3] , V[2] , V[2] , -V[3] ] == {{(-2*I)*gw^2, 0}, {I*gw^2, 0}, {I*gw^2, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gw^2, 0}, {(-I)*gw^2, 0}, {(2*I)*gw^2, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[6] ] == {{(-I/2)*g1*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{(I*gw*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{(I/2)*gw*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[6] ] == {{(-I/2)*g1*IndexDelta[e1x2, e2x2], 0}, {(-I)*g1*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{(I*gw*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{(-I/2)*gw*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[6] ] == {{(I/6)*g1*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {((2*I)/3)*g1*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{(I*gw*CKM[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{(I/2)*gw*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[6] ] == {{(I/6)*g1*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {(-I/3)*g1*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{(I*gw*Conjugate[CKM[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{(-I/2)*gw*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gw, 0}, {I*gw, 0}, {0, 0}},

C[ -U[2] , U[31] , -V[3] ] == {{(-I)*gw, 0}, {(-I)*gw, 0}, {0, 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gw, 0}, {I*gw, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{(-I)*gw, 0}, {(-I)*gw, 0}, {0, 0}},

C[ -U[31] , U[2] , V[3] ] == {{(-I)*gw, 0}, {(-I)*gw, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gw, 0}, {I*gw, 0}, {0, 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[5, {e3x2}] ] == {{GS*SUNF[e3x2, e1x1, e2x1], 0}, {GS*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , V[6] , V[6] ] == {{((2*I)*cB*g1^2)/LAMBDA^2, 0}, {(I/2)*g1^2, 0}, {((-2*I)*cB*g1^2)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[6] , V[6] ] == {{((2*I)*cB*g1^2)/LAMBDA^2, 0}, {(I/2)*g1^2, 0}, {((-2*I)*cB*g1^2)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[6] , V[6] ] == {{((2*I)*cB*g1^2)/LAMBDA^2, 0}, {(I/2)*g1^2, 0}, {((-2*I)*cB*g1^2)/LAMBDA^2, 0}},

C[ S[2] , S[1] , V[6] ] == {{-g1/2, 0}, {g1/2, 0}},

C[ S[3] , -S[3] , V[6] ] == {{(I/2)*g1, 0}, {(-I/2)*g1, 0}},

C[ S[2] , -S[3] , V[6] , V[3] ] == {{((-I)*cWB*g1*gw)/LAMBDA^2, 0}, {(-I/2)*g1*gw, 0}, {(I*cWB*g1*gw)/LAMBDA^2, 0}},

C[ -S[3] , S[10] , V[60] , V[3] ] == {{-((cWB*g1*gw)/LAMBDA^2), 0}, {-(g1*gw)/2, 0}, {(cWB*g1*gw)/LAMBDA^2, 0}},

C[ -S[3] , S[1] , V[6] , V[3] ] == {{-((cWB*g1*gw)/LAMBDA^2), 0}, {-(g1*gw)/2, 0}, {(cWB*g1*gw)/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I/2)*gw, 0}, {(I/2)*gw, 0}},

C[ -S[3] , S[1] , V[3] ] == {{gw/2, 0}, {-gw/2, 0}},

C[ -S[3] , S[10] , V[3] ] == {{0, 0}, {gw, 0}},

C[ S[2] , S[2] , V[6] , V[2] ] == {{((-I)*cWB*g1*gw)/LAMBDA^2, 0}, {(-I/2)*g1*gw, 0}, {(I*cWB*g1*gw)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[6] , V[2] ] == {{(I*cWB*g1*gw)/LAMBDA^2, 0}, {(I/2)*g1*gw, 0}, {((-I)*cWB*g1*gw)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[6] , V[2] ] == {{((-I)*cWB*g1*gw)/LAMBDA^2, 0}, {(-I/2)*g1*gw, 0}, {(I*cWB*g1*gw)/LAMBDA^2, 0}},

C[ S[2] , S[1] , V[2] ] == {{gw/2, 0}, {-gw/2, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(I/2)*gw, 0}, {(-I/2)*gw, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((2*I)*cW*gw^2)/LAMBDA^2, 0}, {(I/2)*gw^2, 0}, {((-2*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((2*I)*cW*gw^2)/LAMBDA^2, 0}, {(I/2)*gw^2, 0}, {((-2*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((2*I)*cW*gw^2)/LAMBDA^2, 0}, {(I/2)*gw^2, 0}, {((-2*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[2] , S[3] , V[6] , -V[3] ] == {{((-I)*cWB*g1*gw)/LAMBDA^2, 0}, {(-I/2)*g1*gw, 0}, {(I*cWB*g1*gw)/LAMBDA^2, 0}},

C[ S[3] , S[1] , V[6] , -V[3] ] == {{(cWB*g1*gw)/LAMBDA^2, 0}, {(g1*gw)/2, 0}, {-((cWB*g1*gw)/LAMBDA^2), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(I/2)*gw, 0}, {(-I/2)*gw, 0}},

C[ S[3] , S[1] , -V[3] ] == {{gw/2, 0}, {-gw/2, 0}},

C[ S[3] , S[10] , -V[3] ] == {{0, 0}, {gw, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((2*I)*cW*gw^2)/LAMBDA^2, 0}, {(I/2)*gw^2, 0}, {((-2*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((2*I)*cW*gw^2)/LAMBDA^2, 0}, {(I/2)*gw^2, 0}, {((-2*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((2*I)*cW*gw^2)/LAMBDA^2, 0}, {(I/2)*gw^2, 0}, {((-2*I)*cW*gw^2)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[5, {e1x2}] , V[5, {e2x2}] ] == {{((2*I)*cG*GS^2*IndexDelta[e1x2, e2x2])/LAMBDA^2, 0}, {0, 0}, {((-2*I)*cG*GS^2*IndexDelta[e1x2, e2x2])/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[5, {e1x2}] , V[5, {e2x2}] ] == {{((2*I)*cG*GS^2*IndexDelta[e1x2, e2x2])/LAMBDA^2, 0}, {0, 0}, {((-2*I)*cG*GS^2*IndexDelta[e1x2, e2x2])/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[5, {e1x2}] , V[5, {e2x2}] ] == {{((2*I)*cG*GS^2*IndexDelta[e1x2, e2x2])/LAMBDA^2, 0}, {0, 0}, {((-2*I)*cG*GS^2*IndexDelta[e1x2, e2x2])/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(-2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}, {(2*cG*GS^3*SUNF[e1x2, e2x2, e3x2])/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{((-2*I)*cG*GS^4*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/LAMBDA^2, 0}, {((2*I)*cG*GS^4*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/LAMBDA^2, 0}, {((2*I)*cG*GS^4*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{((-2*I)*cG*GS^4*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/LAMBDA^2, 0}, {((2*I)*cG*GS^4*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/LAMBDA^2, 0}, {((2*I)*cG*GS^4*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{((-2*I)*cG*GS^4*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/LAMBDA^2, 0}, {((2*I)*cG*GS^4*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/LAMBDA^2, 0}, {((2*I)*cG*GS^4*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/LAMBDA^2, 0}},

C[ S[2] , -S[3] , V[6] , V[3] , V[2] ] == {{(I*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {((-I)*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , S[1] , V[6] , V[3] , V[2] ] == {{(cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {-((cWB*g1*gw^2)/LAMBDA^2), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , V[3] , V[2] , -V[3] ] == {{((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}, {((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , V[2] , -V[3] ] == {{((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}, {((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , V[2] , -V[3] ] == {{((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}, {((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((-2*I)*cW*gw^3)/LAMBDA^2, 0}, {((2*I)*cW*gw^3)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[6] , V[3] , -V[3] ] == {{((-I)*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {(I*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[6] , V[3] , -V[3] ] == {{(I*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {((-I)*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , V[6] , V[3] , -V[3] ] == {{((-I)*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {(I*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[3] , V[6] , V[2] , -V[3] ] == {{(I*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {((-I)*cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[1] , V[6] , V[2] , -V[3] ] == {{-((cWB*g1*gw^2)/LAMBDA^2), 0}, {0, 0}, {(cWB*g1*gw^2)/LAMBDA^2, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , V[3] , V[2] , V[2] , -V[3] ] == {{((4*I)*cW*gw^4)/LAMBDA^2, 0}, {((-2*I)*cW*gw^4)/LAMBDA^2, 0}, {((-2*I)*cW*gw^4)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , V[2] , V[2] , -V[3] ] == {{((4*I)*cW*gw^4)/LAMBDA^2, 0}, {((-2*I)*cW*gw^4)/LAMBDA^2, 0}, {((-2*I)*cW*gw^4)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , V[2] , V[2] , -V[3] ] == {{((4*I)*cW*gw^4)/LAMBDA^2, 0}, {((-2*I)*cW*gw^4)/LAMBDA^2, 0}, {((-2*I)*cW*gw^4)/LAMBDA^2, 0}},

C[ S[2] , S[2] , V[3] , V[3] , -V[3] , -V[3] ] == {{((2*I)*cW*gw^4)/LAMBDA^2, 0}, {((2*I)*cW*gw^4)/LAMBDA^2, 0}, {((-4*I)*cW*gw^4)/LAMBDA^2, 0}},

C[ S[3] , -S[3] , V[3] , V[3] , -V[3] , -V[3] ] == {{((2*I)*cW*gw^4)/LAMBDA^2, 0}, {((2*I)*cW*gw^4)/LAMBDA^2, 0}, {((-4*I)*cW*gw^4)/LAMBDA^2, 0}},

C[ S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{((2*I)*cW*gw^4)/LAMBDA^2, 0}, {((2*I)*cW*gw^4)/LAMBDA^2, 0}, {((-4*I)*cW*gw^4)/LAMBDA^2, 0}}

}

