(* Generated by smeft_gaugefix.m *)
(* Ghost vertices in FeynRules format *)

GhostVertices = {{{}, (G0*ghWm*ghWmbar*GW^2*vev*xiW)/4 - (G0*ghWp*ghWpbar*GW^2*vev*xiW)/4 - 
   ((I/4)*G1^4*ghWpbar*ghZ*GP*GW*vev*xiW)/(G1^2 + GW^2)^(3/2) - 
   ((I/4)*G1^4*ghWmbar*ghZ*GPbar*GW*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1^3*ghA*ghWpbar*GP*GW^2*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1^3*ghA*ghWmbar*GPbar*GW^2*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1*ghA*ghWpbar*GP*GW^4*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1*ghA*ghWmbar*GPbar*GW^4*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/4)*ghWpbar*ghZ*GP*GW^5*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/4)*ghWmbar*ghZ*GPbar*GW^5*vev*xiW)/(G1^2 + GW^2)^(3/2) + 
   (I/4)*ghWm*ghWmbar*GW^2*H*vev*xiW + (I/4)*ghWp*ghWpbar*GW^2*H*vev*xiW + 
   ((I/4)*G1^4*ghWpbar*ghZ*GP*GW*Lam*TphiB*vev^3*xiW)/(G1^2 + GW^2)^(3/2) - 
   ((I/4)*G1^6*ghWpbar*ghZ*GP*GW*Lam*TphiB*vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/4)*G1^4*ghWmbar*ghZ*GPbar*GW*Lam*TphiB*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) - ((I/4)*G1^6*ghWmbar*ghZ*GPbar*GW*Lam*TphiB*vev^3*
     xiW)/(G1^2 + GW^2)^(3/2) + (((3*I)/4)*G1^2*ghWpbar*ghZ*GP*GW^3*Lam*TphiB*
     vev^3*xiW)/(G1^2 + GW^2)^(3/2) - (((3*I)/4)*G1^4*ghWpbar*ghZ*GP*GW^3*Lam*
     TphiB*vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   (((3*I)/4)*G1^2*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiB*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) - (((3*I)/4)*G1^4*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiB*
     vev^3*xiW)/(G1^2 + GW^2)^(3/2) - ((I/2)*G1*ghA*ghWpbar*GP*GW^4*Lam*TphiB*
     vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1^3*ghA*ghWpbar*GP*GW^4*Lam*TphiB*vev^3*xiW)/(G1^2 + GW^2)^(3/2) - 
   ((I/2)*G1*ghA*ghWmbar*GPbar*GW^4*Lam*TphiB*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) + ((I/2)*G1^3*ghA*ghWmbar*GPbar*GW^4*Lam*TphiB*vev^3*
     xiW)/(G1^2 + GW^2)^(3/2) - ((I/2)*G1^3*ghA*ghWpbar*GP*GW^2*Lam*TphiW*
     vev^3*xiW)/(G1^2 + GW^2)^(3/2) - ((I/2)*G1^3*ghA*ghWmbar*GPbar*GW^2*Lam*
     TphiW*vev^3*xiW)/(G1^2 + GW^2)^(3/2) - 
   (((3*I)/4)*G1^2*ghWpbar*ghZ*GP*GW^3*Lam*TphiW*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) - (((3*I)/4)*G1^2*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiW*
     vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1^3*ghA*ghWpbar*GP*GW^4*Lam*TphiW*vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/2)*G1^3*ghA*ghWmbar*GPbar*GW^4*Lam*TphiW*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) - ((I/4)*ghWpbar*ghZ*GP*GW^5*Lam*TphiW*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) + (((3*I)/4)*G1^2*ghWpbar*ghZ*GP*GW^5*Lam*TphiW*vev^3*
     xiW)/(G1^2 + GW^2)^(3/2) - ((I/4)*ghWmbar*ghZ*GPbar*GW^5*Lam*TphiW*vev^3*
     xiW)/(G1^2 + GW^2)^(3/2) + (((3*I)/4)*G1^2*ghWmbar*ghZ*GPbar*GW^5*Lam*
     TphiW*vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/4)*ghWpbar*ghZ*GP*GW^7*Lam*TphiW*vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/4)*ghWmbar*ghZ*GPbar*GW^7*Lam*TphiW*vev^3*xiW)/(G1^2 + GW^2)^(3/2) + 
   ((I/4)*G1^4*ghWpbar*ghZ*GP*GW^3*Lam*TphiWB*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) + ((I/4)*G1^4*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiWB*vev^3*
     xiW)/(G1^2 + GW^2)^(3/2) - ((I/2)*G1^3*ghA*ghWpbar*GP*GW^4*Lam*TphiWB*
     vev^3*xiW)/(G1^2 + GW^2)^(3/2) - ((I/2)*G1^3*ghA*ghWmbar*GPbar*GW^4*Lam*
     TphiWB*vev^3*xiW)/(G1^2 + GW^2)^(3/2) - 
   ((I/4)*G1^2*ghWpbar*ghZ*GP*GW^5*Lam*TphiWB*vev^3*xiW)/
    (G1^2 + GW^2)^(3/2) - ((I/4)*G1^2*ghWmbar*ghZ*GPbar*GW^5*Lam*TphiWB*vev^3*
     xiW)/(G1^2 + GW^2)^(3/2) - ((I/4)*G1^2*ghWm*ghZbar*GP*GW*vev*xiZ)/
    Sqrt[G1^2 + GW^2] - ((I/4)*G1^2*ghWp*ghZbar*GPbar*GW*vev*xiZ)/
    Sqrt[G1^2 + GW^2] - ((I/4)*ghWm*ghZbar*GP*GW^3*vev*xiZ)/
    Sqrt[G1^2 + GW^2] - ((I/4)*ghWp*ghZbar*GPbar*GW^3*vev*xiZ)/
    Sqrt[G1^2 + GW^2] + (I/4)*G1^2*ghZ*ghZbar*H*vev*xiZ + 
   (I/4)*ghZ*ghZbar*GW^2*H*vev*xiZ + (((3*I)/4)*G1^2*ghWm*ghZbar*GP*GW*Lam*
     TphiB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   (((3*I)/4)*G1^4*ghWm*ghZbar*GP*GW*Lam*TphiB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   (((3*I)/4)*G1^2*ghWp*ghZbar*GPbar*GW*Lam*TphiB*vev^3*xiZ)/
    Sqrt[G1^2 + GW^2] - (((3*I)/4)*G1^4*ghWp*ghZbar*GPbar*GW*Lam*TphiB*vev^3*
     xiZ)/Sqrt[G1^2 + GW^2] - ((I/2)*G1*ghAbar*ghWm*GP*GW^2*Lam*TphiB*vev^3*
     xiZ)/Sqrt[G1^2 + GW^2] + ((I/2)*G1^3*ghAbar*ghWm*GP*GW^2*Lam*TphiB*vev^3*
     xiZ)/Sqrt[G1^2 + GW^2] - ((I/2)*G1*ghAbar*ghWp*GPbar*GW^2*Lam*TphiB*
     vev^3*xiZ)/Sqrt[G1^2 + GW^2] + ((I/2)*G1^3*ghAbar*ghWp*GPbar*GW^2*Lam*
     TphiB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - I*G1^2*ghZ*ghZbar*H*Lam*TphiB*vev^3*
    xiZ + I*G1^4*ghZ*ghZbar*H*Lam*TphiB*vev^3*xiZ + 
   (I/2)*G1*ghAbar*ghZ*GW*H*Lam*TphiB*vev^3*xiZ - 
   (I/2)*G1^3*ghAbar*ghZ*GW*H*Lam*TphiB*vev^3*xiZ + 
   ((I/2)*G1*ghAbar*ghWm*GP*GW^2*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   ((I/2)*G1*ghAbar*ghWp*GPbar*GW^2*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   (((3*I)/4)*ghWm*ghZbar*GP*GW^3*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   (((3*I)/4)*ghWp*ghZbar*GPbar*GW^3*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   ((I/2)*G1*ghAbar*ghWm*GP*GW^4*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   ((I/2)*G1*ghAbar*ghWp*GPbar*GW^4*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   (((3*I)/4)*ghWm*ghZbar*GP*GW^5*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   (((3*I)/4)*ghWp*ghZbar*GPbar*GW^5*Lam*TphiW*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   (I/2)*G1*ghAbar*ghZ*GW*H*Lam*TphiW*vev^3*xiZ - 
   I*ghZ*ghZbar*GW^2*H*Lam*TphiW*vev^3*xiZ + (I/2)*G1*ghAbar*ghZ*GW^3*H*Lam*
    TphiW*vev^3*xiZ + I*ghZ*ghZbar*GW^4*H*Lam*TphiW*vev^3*xiZ + 
   ((I/4)*G1^2*ghAbar*ghWm*GP*GW*Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   ((I/4)*G1^2*ghAbar*ghWp*GPbar*GW*Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   ((I/4)*G1^3*ghAbar*ghWm*GP*GW^2*Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   ((I/2)*G1*ghWm*ghZbar*GP*GW^2*Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   ((I/4)*G1^3*ghAbar*ghWp*GPbar*GW^2*Lam*TphiWB*vev^3*xiZ)/
    Sqrt[G1^2 + GW^2] + ((I/2)*G1*ghWp*ghZbar*GPbar*GW^2*Lam*TphiWB*vev^3*
     xiZ)/Sqrt[G1^2 + GW^2] - ((I/4)*ghAbar*ghWm*GP*GW^3*Lam*TphiWB*vev^3*
     xiZ)/Sqrt[G1^2 + GW^2] - (((3*I)/4)*G1^2*ghWm*ghZbar*GP*GW^3*Lam*TphiWB*
     vev^3*xiZ)/Sqrt[G1^2 + GW^2] - ((I/4)*ghAbar*ghWp*GPbar*GW^3*Lam*TphiWB*
     vev^3*xiZ)/Sqrt[G1^2 + GW^2] - (((3*I)/4)*G1^2*ghWp*ghZbar*GPbar*GW^3*
     Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   ((I/4)*G1*ghAbar*ghWm*GP*GW^4*Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] + 
   ((I/4)*G1*ghAbar*ghWp*GPbar*GW^4*Lam*TphiWB*vev^3*xiZ)/Sqrt[G1^2 + GW^2] - 
   (I/4)*G1^2*ghAbar*ghZ*H*Lam*TphiWB*vev^3*xiZ + 
   (I/4)*G1^3*ghAbar*ghZ*GW*H*Lam*TphiWB*vev^3*xiZ - 
   (I/2)*G1*ghZ*ghZbar*GW*H*Lam*TphiWB*vev^3*xiZ + 
   (I/4)*ghAbar*ghZ*GW^2*H*Lam*TphiWB*vev^3*xiZ + 
   I*G1^2*ghZ*ghZbar*GW^2*H*Lam*TphiWB*vev^3*xiZ - 
   (I/4)*G1*ghAbar*ghZ*GW^3*H*Lam*TphiWB*vev^3*xiZ - 
   (G1^3*ghWm*GW*A[Index[Lorentz, mu$1]]*del[ghWmbar, Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1*ghWm*GW^3*A[Index[Lorentz, mu$1]]*
     del[ghWmbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1*ghWm*GW^3*Lam*TphiB*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWmbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWm*GW^3*Lam*TphiB*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWmbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWm*GW*Lam*TphiW*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWmbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWm*GW^3*Lam*TphiW*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWmbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWm*GW^3*Lam*TphiWB*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWmbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWp*GW*A[Index[Lorentz, mu$1]]*del[ghWpbar, Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1*ghWp*GW^3*A[Index[Lorentz, mu$1]]*
     del[ghWpbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1*ghWp*GW^3*Lam*TphiB*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWpbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWp*GW^3*Lam*TphiB*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWpbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWp*GW*Lam*TphiW*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWpbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWp*GW^3*Lam*TphiW*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWpbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWp*GW^3*Lam*TphiWB*vev^2*A[Index[Lorentz, mu$1]]*
     del[ghWpbar, Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (I*G1^2*GS*del[ghGbar[Index[Gluon, Gluon$1]], Index[Lorentz, mu$1]]*
     f[Index[Gluon, Gluon$1], Index[Gluon, Gluon$2], Index[Gluon, Gluon$3]]*
     G[Index[Lorentz, mu$1], Index[Gluon, Gluon$3]]*
     ghG[Index[Gluon, Gluon$2]])/(G1^2 + GW^2) - 
   (I*GS*GW^2*del[ghGbar[Index[Gluon, Gluon$1]], Index[Lorentz, mu$1]]*
     f[Index[Gluon, Gluon$1], Index[Gluon, Gluon$2], Index[Gluon, Gluon$3]]*
     G[Index[Lorentz, mu$1], Index[Gluon, Gluon$3]]*
     ghG[Index[Gluon, Gluon$2]])/(G1^2 + GW^2) + 
   (G1^3*ghWm*GW*del[ghAbar, Index[Lorentz, mu$1]]*W[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1*ghWm*GW^3*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1*ghWm*GW^3*Lam*TphiB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWm*GW^3*Lam*TphiB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWm*GW*Lam*TphiW*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWm*GW^3*Lam*TphiW*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^2*ghWm*GW^2*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWm*GW^3*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (ghWm*GW^4*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghA*GW*del[ghWpbar, Index[Lorentz, mu$1]]*W[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^2*ghZ*GW^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1*ghA*GW^3*del[ghWpbar, Index[Lorentz, mu$1]]*W[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (ghZ*GW^4*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^2*ghZ*GW^2*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^4*ghZ*GW^2*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1*ghA*GW^3*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghA*GW^3*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghA*GW*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (2*G1^2*ghZ*GW^2*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghA*GW^3*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (ghZ*GW^4*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (2*G1^2*ghZ*GW^4*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (ghZ*GW^6*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^4*ghZ*GW^2*Lam*TphiWB*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghA*GW^3*Lam*TphiWB*vev^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^2*ghWm*GW^2*del[ghZbar, Index[Lorentz, mu$1]]*W[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (ghWm*GW^4*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^2*ghWm*GW^2*Lam*TphiB*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^4*ghWm*GW^2*Lam*TphiB*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (2*G1^2*ghWm*GW^2*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (ghWm*GW^4*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (2*G1^2*ghWm*GW^4*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (ghWm*GW^6*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWm*GW*Lam*TphiWB*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^4*ghWm*GW^2*Lam*TphiWB*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1*ghWm*GW^3*Lam*TphiWB*vev^2*del[ghZbar, Index[Lorentz, mu$1]]*
     W[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWp*GW*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1*ghWp*GW^3*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1*ghWp*GW^3*Lam*TphiB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWp*GW^3*Lam*TphiB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWp*GW*Lam*TphiW*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^3*ghWp*GW^3*Lam*TphiW*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (G1^2*ghWp*GW^2*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghWp*GW^3*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (ghWp*GW^4*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^3*ghA*GW*del[ghWmbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1^2*ghZ*GW^2*del[ghWmbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (G1*ghA*GW^3*del[ghWmbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (ghZ*GW^4*del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^2*ghZ*GW^2*Lam*TphiB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^4*ghZ*GW^2*Lam*TphiB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1*ghA*GW^3*Lam*TphiB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^3*ghA*GW^3*Lam*TphiB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^3*ghA*GW*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (2*G1^2*ghZ*GW^2*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^3*ghA*GW^3*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (ghZ*GW^4*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (2*G1^2*ghZ*GW^4*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (ghZ*GW^6*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^4*ghZ*GW^2*Lam*TphiWB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^3*ghA*GW^3*Lam*TphiWB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^2*ghWp*GW^2*del[ghZbar, Index[Lorentz, mu$1]]*
     Wbar[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (ghWp*GW^4*del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^2*ghWp*GW^2*Lam*TphiB*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^4*ghWp*GW^2*Lam*TphiB*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (2*G1^2*ghWp*GW^2*Lam*TphiW*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (ghWp*GW^4*Lam*TphiW*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (2*G1^2*ghWp*GW^4*Lam*TphiW*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (ghWp*GW^6*Lam*TphiW*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^3*ghWp*GW*Lam*TphiWB*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^4*ghWp*GW^2*Lam*TphiWB*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1*ghWp*GW^3*Lam*TphiWB*vev^2*
     del[ghZbar, Index[Lorentz, mu$1]]*Wbar[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^2*ghWm*GW^2*del[ghWmbar, Index[Lorentz, mu$1]]*
     Z[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) - 
   (ghWm*GW^4*del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^2*ghWm*GW^2*Lam*TphiB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^4*ghWm*GW^2*Lam*TphiB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (2*G1^2*ghWm*GW^2*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (ghWm*GW^4*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (2*G1^2*ghWm*GW^4*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (ghWm*GW^6*Lam*TphiW*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^4*ghWm*GW^2*Lam*TphiWB*vev^2*
     del[ghWmbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^2*ghWp*GW^2*del[ghWpbar, Index[Lorentz, mu$1]]*
     Z[Index[Lorentz, mu$1]])/(G1^2 + GW^2)^(3/2) + 
   (ghWp*GW^4*del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^2*ghWp*GW^2*Lam*TphiB*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (G1^4*ghWp*GW^2*Lam*TphiB*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (2*G1^2*ghWp*GW^2*Lam*TphiW*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) - (ghWp*GW^4*Lam*TphiW*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (2*G1^2*ghWp*GW^4*Lam*TphiW*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (ghWp*GW^6*Lam*TphiW*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2) + (G1^4*ghWp*GW^2*Lam*TphiWB*vev^2*
     del[ghWpbar, Index[Lorentz, mu$1]]*Z[Index[Lorentz, mu$1]])/
    (G1^2 + GW^2)^(3/2)}}


GhostLagrangian = (-4*G1^4*ghWpbar*ghZ*GP*GW*vev*xiW - 4*G1^4*ghWmbar*ghZ*GPbar*GW*vev*xiW + 
  8*G1^3*ghA*ghWpbar*GP*GW^2*vev*xiW + 8*G1^3*ghA*ghWmbar*GPbar*GW^2*vev*
   xiW + 8*G1*ghA*ghWpbar*GP*GW^4*vev*xiW + 8*G1*ghA*ghWmbar*GPbar*GW^4*vev*
   xiW + 4*ghWpbar*ghZ*GP*GW^5*vev*xiW + 4*ghWmbar*ghZ*GPbar*GW^5*vev*xiW - 
  (4*I)*G0*G1^2*ghWm*ghWmbar*GW^2*Sqrt[G1^2 + GW^2]*vev*xiW + 
  (4*I)*G0*G1^2*ghWp*ghWpbar*GW^2*Sqrt[G1^2 + GW^2]*vev*xiW - 
  (4*I)*G0*ghWm*ghWmbar*GW^4*Sqrt[G1^2 + GW^2]*vev*xiW + 
  (4*I)*G0*ghWp*ghWpbar*GW^4*Sqrt[G1^2 + GW^2]*vev*xiW + 
  4*G1^2*ghWm*ghWmbar*GW^2*Sqrt[G1^2 + GW^2]*H*vev*xiW + 
  4*G1^2*ghWp*ghWpbar*GW^2*Sqrt[G1^2 + GW^2]*H*vev*xiW + 
  4*ghWm*ghWmbar*GW^4*Sqrt[G1^2 + GW^2]*H*vev*xiW + 
  4*ghWp*ghWpbar*GW^4*Sqrt[G1^2 + GW^2]*H*vev*xiW + 
  4*G1^2*ghWm*ghWmbar*GW^2*Sqrt[G1^2 + GW^2]*vev^2*xiW + 
  4*G1^2*ghWp*ghWpbar*GW^2*Sqrt[G1^2 + GW^2]*vev^2*xiW + 
  4*ghWm*ghWmbar*GW^4*Sqrt[G1^2 + GW^2]*vev^2*xiW + 
  4*ghWp*ghWpbar*GW^4*Sqrt[G1^2 + GW^2]*vev^2*xiW + 
  4*G1^4*ghWpbar*ghZ*GP*GW*Lam*TphiB*vev^3*xiW - 
  4*G1^6*ghWpbar*ghZ*GP*GW*Lam*TphiB*vev^3*xiW + 
  4*G1^4*ghWmbar*ghZ*GPbar*GW*Lam*TphiB*vev^3*xiW - 
  4*G1^6*ghWmbar*ghZ*GPbar*GW*Lam*TphiB*vev^3*xiW + 
  12*G1^2*ghWpbar*ghZ*GP*GW^3*Lam*TphiB*vev^3*xiW - 
  12*G1^4*ghWpbar*ghZ*GP*GW^3*Lam*TphiB*vev^3*xiW + 
  12*G1^2*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiB*vev^3*xiW - 
  12*G1^4*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiB*vev^3*xiW - 
  8*G1*ghA*ghWpbar*GP*GW^4*Lam*TphiB*vev^3*xiW + 
  8*G1^3*ghA*ghWpbar*GP*GW^4*Lam*TphiB*vev^3*xiW - 
  8*G1*ghA*ghWmbar*GPbar*GW^4*Lam*TphiB*vev^3*xiW + 
  8*G1^3*ghA*ghWmbar*GPbar*GW^4*Lam*TphiB*vev^3*xiW - 
  8*G1^3*ghA*ghWpbar*GP*GW^2*Lam*TphiW*vev^3*xiW - 
  8*G1^3*ghA*ghWmbar*GPbar*GW^2*Lam*TphiW*vev^3*xiW - 
  12*G1^2*ghWpbar*ghZ*GP*GW^3*Lam*TphiW*vev^3*xiW - 
  12*G1^2*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiW*vev^3*xiW + 
  8*G1^3*ghA*ghWpbar*GP*GW^4*Lam*TphiW*vev^3*xiW + 
  8*G1^3*ghA*ghWmbar*GPbar*GW^4*Lam*TphiW*vev^3*xiW - 
  4*ghWpbar*ghZ*GP*GW^5*Lam*TphiW*vev^3*xiW + 12*G1^2*ghWpbar*ghZ*GP*GW^5*Lam*
   TphiW*vev^3*xiW - 4*ghWmbar*ghZ*GPbar*GW^5*Lam*TphiW*vev^3*xiW + 
  12*G1^2*ghWmbar*ghZ*GPbar*GW^5*Lam*TphiW*vev^3*xiW + 
  4*ghWpbar*ghZ*GP*GW^7*Lam*TphiW*vev^3*xiW + 4*ghWmbar*ghZ*GPbar*GW^7*Lam*
   TphiW*vev^3*xiW + 4*G1^4*ghWpbar*ghZ*GP*GW^3*Lam*TphiWB*vev^3*xiW + 
  4*G1^4*ghWmbar*ghZ*GPbar*GW^3*Lam*TphiWB*vev^3*xiW - 
  8*G1^3*ghA*ghWpbar*GP*GW^4*Lam*TphiWB*vev^3*xiW - 
  8*G1^3*ghA*ghWmbar*GPbar*GW^4*Lam*TphiWB*vev^3*xiW - 
  4*G1^2*ghWpbar*ghZ*GP*GW^5*Lam*TphiWB*vev^3*xiW - 
  4*G1^2*ghWmbar*ghZ*GPbar*GW^5*Lam*TphiWB*vev^3*xiW - 
  4*G1^4*ghWm*ghZbar*GP*GW*vev*xiZ - 4*G1^4*ghWp*ghZbar*GPbar*GW*vev*xiZ - 
  8*G1^2*ghWm*ghZbar*GP*GW^3*vev*xiZ - 8*G1^2*ghWp*ghZbar*GPbar*GW^3*vev*
   xiZ - 4*ghWm*ghZbar*GP*GW^5*vev*xiZ - 4*ghWp*ghZbar*GPbar*GW^5*vev*xiZ + 
  4*G1^4*ghZ*ghZbar*Sqrt[G1^2 + GW^2]*H*vev*xiZ + 
  8*G1^2*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*H*vev*xiZ + 
  4*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*H*vev*xiZ + 
  4*G1^4*ghZ*ghZbar*Sqrt[G1^2 + GW^2]*vev^2*xiZ + 
  8*G1^2*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*vev^2*xiZ + 
  4*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*vev^2*xiZ + 
  12*G1^4*ghWm*ghZbar*GP*GW*Lam*TphiB*vev^3*xiZ - 
  12*G1^6*ghWm*ghZbar*GP*GW*Lam*TphiB*vev^3*xiZ + 
  12*G1^4*ghWp*ghZbar*GPbar*GW*Lam*TphiB*vev^3*xiZ - 
  12*G1^6*ghWp*ghZbar*GPbar*GW*Lam*TphiB*vev^3*xiZ - 
  8*G1^3*ghAbar*ghWm*GP*GW^2*Lam*TphiB*vev^3*xiZ + 
  8*G1^5*ghAbar*ghWm*GP*GW^2*Lam*TphiB*vev^3*xiZ - 
  8*G1^3*ghAbar*ghWp*GPbar*GW^2*Lam*TphiB*vev^3*xiZ + 
  8*G1^5*ghAbar*ghWp*GPbar*GW^2*Lam*TphiB*vev^3*xiZ + 
  12*G1^2*ghWm*ghZbar*GP*GW^3*Lam*TphiB*vev^3*xiZ - 
  12*G1^4*ghWm*ghZbar*GP*GW^3*Lam*TphiB*vev^3*xiZ + 
  12*G1^2*ghWp*ghZbar*GPbar*GW^3*Lam*TphiB*vev^3*xiZ - 
  12*G1^4*ghWp*ghZbar*GPbar*GW^3*Lam*TphiB*vev^3*xiZ - 
  8*G1*ghAbar*ghWm*GP*GW^4*Lam*TphiB*vev^3*xiZ + 
  8*G1^3*ghAbar*ghWm*GP*GW^4*Lam*TphiB*vev^3*xiZ - 
  8*G1*ghAbar*ghWp*GPbar*GW^4*Lam*TphiB*vev^3*xiZ + 
  8*G1^3*ghAbar*ghWp*GPbar*GW^4*Lam*TphiB*vev^3*xiZ - 
  16*G1^4*ghZ*ghZbar*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ + 
  16*G1^6*ghZ*ghZbar*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ + 
  8*G1^3*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ - 
  8*G1^5*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ - 
  16*G1^2*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ + 
  16*G1^4*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ + 
  8*G1*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ - 
  8*G1^3*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*H*Lam*TphiB*vev^3*xiZ + 
  8*G1^3*ghAbar*ghWm*GP*GW^2*Lam*TphiW*vev^3*xiZ + 
  8*G1^3*ghAbar*ghWp*GPbar*GW^2*Lam*TphiW*vev^3*xiZ + 
  12*G1^2*ghWm*ghZbar*GP*GW^3*Lam*TphiW*vev^3*xiZ + 
  12*G1^2*ghWp*ghZbar*GPbar*GW^3*Lam*TphiW*vev^3*xiZ + 
  8*G1*ghAbar*ghWm*GP*GW^4*Lam*TphiW*vev^3*xiZ - 
  8*G1^3*ghAbar*ghWm*GP*GW^4*Lam*TphiW*vev^3*xiZ + 
  8*G1*ghAbar*ghWp*GPbar*GW^4*Lam*TphiW*vev^3*xiZ - 
  8*G1^3*ghAbar*ghWp*GPbar*GW^4*Lam*TphiW*vev^3*xiZ + 
  12*ghWm*ghZbar*GP*GW^5*Lam*TphiW*vev^3*xiZ - 12*G1^2*ghWm*ghZbar*GP*GW^5*
   Lam*TphiW*vev^3*xiZ + 12*ghWp*ghZbar*GPbar*GW^5*Lam*TphiW*vev^3*xiZ - 
  12*G1^2*ghWp*ghZbar*GPbar*GW^5*Lam*TphiW*vev^3*xiZ - 
  8*G1*ghAbar*ghWm*GP*GW^6*Lam*TphiW*vev^3*xiZ - 
  8*G1*ghAbar*ghWp*GPbar*GW^6*Lam*TphiW*vev^3*xiZ - 
  12*ghWm*ghZbar*GP*GW^7*Lam*TphiW*vev^3*xiZ - 12*ghWp*ghZbar*GPbar*GW^7*Lam*
   TphiW*vev^3*xiZ - 8*G1^3*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*
   xiZ - 16*G1^2*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ - 
  8*G1*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ + 
  8*G1^3*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ - 
  16*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ + 
  16*G1^2*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ + 
  8*G1*ghAbar*ghZ*GW^5*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ + 
  16*ghZ*ghZbar*GW^6*Sqrt[G1^2 + GW^2]*H*Lam*TphiW*vev^3*xiZ + 
  4*G1^4*ghAbar*ghWm*GP*GW*Lam*TphiWB*vev^3*xiZ + 
  4*G1^4*ghAbar*ghWp*GPbar*GW*Lam*TphiWB*vev^3*xiZ - 
  4*G1^5*ghAbar*ghWm*GP*GW^2*Lam*TphiWB*vev^3*xiZ + 
  8*G1^3*ghWm*ghZbar*GP*GW^2*Lam*TphiWB*vev^3*xiZ - 
  4*G1^5*ghAbar*ghWp*GPbar*GW^2*Lam*TphiWB*vev^3*xiZ + 
  8*G1^3*ghWp*ghZbar*GPbar*GW^2*Lam*TphiWB*vev^3*xiZ - 
  12*G1^4*ghWm*ghZbar*GP*GW^3*Lam*TphiWB*vev^3*xiZ - 
  12*G1^4*ghWp*ghZbar*GPbar*GW^3*Lam*TphiWB*vev^3*xiZ + 
  8*G1*ghWm*ghZbar*GP*GW^4*Lam*TphiWB*vev^3*xiZ + 
  8*G1*ghWp*ghZbar*GPbar*GW^4*Lam*TphiWB*vev^3*xiZ - 
  4*ghAbar*ghWm*GP*GW^5*Lam*TphiWB*vev^3*xiZ - 12*G1^2*ghWm*ghZbar*GP*GW^5*
   Lam*TphiWB*vev^3*xiZ - 4*ghAbar*ghWp*GPbar*GW^5*Lam*TphiWB*vev^3*xiZ - 
  12*G1^2*ghWp*ghZbar*GPbar*GW^5*Lam*TphiWB*vev^3*xiZ + 
  4*G1*ghAbar*ghWm*GP*GW^6*Lam*TphiWB*vev^3*xiZ + 
  4*G1*ghAbar*ghWp*GPbar*GW^6*Lam*TphiWB*vev^3*xiZ - 
  4*G1^4*ghAbar*ghZ*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ + 
  4*G1^5*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ - 
  8*G1^3*ghZ*ghZbar*GW*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ + 
  16*G1^4*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ - 
  8*G1*ghZ*ghZbar*GW^3*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ + 
  4*ghAbar*ghZ*GW^4*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ + 
  16*G1^2*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ - 
  4*G1*ghAbar*ghZ*GW^5*Sqrt[G1^2 + GW^2]*H*Lam*TphiWB*vev^3*xiZ - 
  16*G1^4*ghZ*ghZbar*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ + 
  16*G1^6*ghZ*ghZbar*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ + 
  8*G1^3*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ - 
  8*G1^5*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ - 
  16*G1^2*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ + 
  16*G1^4*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ + 
  8*G1*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ - 
  8*G1^3*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^4*xiZ - 
  8*G1^3*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ - 
  16*G1^2*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ - 
  8*G1*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ + 
  8*G1^3*ghAbar*ghZ*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ - 
  16*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ + 
  16*G1^2*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ + 
  8*G1*ghAbar*ghZ*GW^5*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ + 
  16*ghZ*ghZbar*GW^6*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^4*xiZ - 
  4*G1^4*ghAbar*ghZ*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ + 
  4*G1^5*ghAbar*ghZ*GW*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ - 
  8*G1^3*ghZ*ghZbar*GW*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ + 
  16*G1^4*ghZ*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ - 
  8*G1*ghZ*ghZbar*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ + 
  4*ghAbar*ghZ*GW^4*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ + 
  16*G1^2*ghZ*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ - 
  4*G1*ghAbar*ghZ*GW^5*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^4*xiZ + 
  (16*I)*G1*GW*(GW^2*(1 - Lam*TphiB*vev^2) + 
    G1^2*(1 - Lam*TphiW*vev^2 + GW^2*Lam*(TphiB + TphiW - TphiWB)*vev^2))*
   A[Index[Lorentz, mu]]*(ghWm*del[ghWmbar, Index[Lorentz, mu]] - 
    ghWp*del[ghWpbar, Index[Lorentz, mu]]) - 16*Sqrt[G1^2 + GW^2]*
   (G1^3*ghZbar*GW*Lam*(2*TphiB - TphiWB)*vev^2 + 
    G1*GW*Lam*(-2*ghAbar*TphiWB + ghZbar*(-2*TphiB + 2*TphiW - 2*GW^2*TphiW + 
        GW^2*TphiWB))*vev^2 - GW^2*(ghAbar - 2*ghAbar*Lam*TphiB*vev^2 + 
      ghZbar*Lam*TphiWB*vev^2) + G1^2*(ghZbar*Lam*TphiWB*vev^2 + 
      ghAbar*(-1 + 2*Lam*TphiW*vev^2 - 2*GW^2*Lam*(TphiB + TphiW - TphiWB)*
         vev^2)))*del[del[ghA, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  16*G1^2*ghWmbar*Sqrt[G1^2 + GW^2]*del[del[ghWm, Index[Lorentz, mu]], 
    Index[Lorentz, mu]] + 16*ghWmbar*GW^2*Sqrt[G1^2 + GW^2]*
   del[del[ghWm, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  16*G1^2*ghWpbar*Sqrt[G1^2 + GW^2]*del[del[ghWp, Index[Lorentz, mu]], 
    Index[Lorentz, mu]] + 16*ghWpbar*GW^2*Sqrt[G1^2 + GW^2]*
   del[del[ghWp, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  16*G1^2*ghZbar*Sqrt[G1^2 + GW^2]*del[del[ghZ, Index[Lorentz, mu]], 
    Index[Lorentz, mu]] + 16*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  32*G1^2*ghZbar*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  32*G1^4*ghZbar*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  32*G1*ghAbar*GW*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  32*G1^3*ghAbar*GW*Sqrt[G1^2 + GW^2]*Lam*TphiB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  32*G1*ghAbar*GW*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  32*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  32*G1*ghAbar*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  32*ghZbar*GW^4*Sqrt[G1^2 + GW^2]*Lam*TphiW*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  16*G1^2*ghAbar*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  16*G1^3*ghAbar*GW*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  32*G1*ghZbar*GW*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  16*ghAbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] + 
  32*G1^2*ghZbar*GW^2*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  16*G1*ghAbar*GW^3*Sqrt[G1^2 + GW^2]*Lam*TphiWB*vev^2*
   del[del[ghZ, Index[Lorentz, mu]], Index[Lorentz, mu]] - 
  16*G1^2*Sqrt[G1^2 + GW^2]*del[ghG[Index[Gluon, aa]], Index[Lorentz, mu]]*
   del[ghGbar[Index[Gluon, aa]], Index[Lorentz, mu]] - 
  16*GW^2*Sqrt[G1^2 + GW^2]*del[ghG[Index[Gluon, aa]], Index[Lorentz, mu]]*
   del[ghGbar[Index[Gluon, aa]], Index[Lorentz, mu]] - 
  16*G1^2*GS*Sqrt[G1^2 + GW^2]*del[ghGbar[Index[Gluon, aa]], 
    Index[Lorentz, mu]]*f[Index[Gluon, aa], Index[Gluon, bb], 
    Index[Gluon, cc]]*G[Index[Lorentz, mu], Index[Gluon, cc]]*
   ghG[Index[Gluon, bb]] - 16*GS*GW^2*Sqrt[G1^2 + GW^2]*
   del[ghGbar[Index[Gluon, aa]], Index[Lorentz, mu]]*
   f[Index[Gluon, aa], Index[Gluon, bb], Index[Gluon, cc]]*
   G[Index[Lorentz, mu], Index[Gluon, cc]]*ghG[Index[Gluon, bb]] - 
  (16*I)*G1^3*ghWm*GW*del[ghAbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*G1*ghWm*GW^3*del[ghAbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1*ghWm*GW^3*Lam*TphiB*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*G1^3*ghWm*GW^3*Lam*TphiB*vev^2*
   del[ghAbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^3*ghWm*GW*Lam*TphiW*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*G1^3*ghWm*GW^3*Lam*TphiW*vev^2*
   del[ghAbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*G1^2*ghWm*GW^2*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*G1^3*ghWm*GW^3*Lam*TphiWB*vev^2*
   del[ghAbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*ghWm*GW^4*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*G1^3*ghA*GW*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^2*ghZ*GW^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*G1*ghA*GW^3*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*ghZ*GW^4*del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^2*ghZ*GW^2*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*G1^4*ghZ*GW^2*Lam*TphiB*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*G1*ghA*GW^3*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*G1^3*ghA*GW^3*Lam*TphiB*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*G1^3*ghA*GW*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (32*I)*G1^2*ghZ*GW^2*Lam*TphiW*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^3*ghA*GW^3*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*ghZ*GW^4*Lam*TphiW*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (32*I)*G1^2*ghZ*GW^4*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*ghZ*GW^6*Lam*TphiW*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^4*ghZ*GW^2*Lam*TphiWB*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*G1^3*ghA*GW^3*Lam*TphiWB*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*G1^2*ghWm*GW^2*del[ghZbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*ghWm*GW^4*del[ghZbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (16*I)*G1^2*ghWm*GW^2*Lam*TphiB*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^4*ghWm*GW^2*Lam*TphiB*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (32*I)*G1^2*ghWm*GW^2*Lam*TphiW*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*ghWm*GW^4*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] - (32*I)*G1^2*ghWm*GW^4*Lam*TphiW*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*ghWm*GW^6*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*G1^3*ghWm*GW*Lam*TphiWB*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] - 
  (16*I)*G1^4*ghWm*GW^2*Lam*TphiWB*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   W[Index[Lorentz, mu]] + (16*I)*G1*ghWm*GW^3*Lam*TphiWB*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*W[Index[Lorentz, mu]] + 
  (16*I)*G1^3*ghWp*GW*del[ghAbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1*ghWp*GW^3*
   del[ghAbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1*ghWp*GW^3*Lam*TphiB*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1^3*ghWp*GW^3*Lam*TphiB*vev^2*
   del[ghAbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1^3*ghWp*GW*Lam*TphiW*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1^3*ghWp*GW^3*Lam*TphiW*vev^2*
   del[ghAbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (16*I)*G1^2*ghWp*GW^2*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*G1^3*ghWp*GW^3*Lam*TphiWB*vev^2*
   del[ghAbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (16*I)*ghWp*GW^4*Lam*TphiWB*vev^2*del[ghAbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*G1^3*ghA*GW*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1^2*ghZ*GW^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*G1*ghA*GW^3*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*ghZ*GW^4*del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1^2*ghZ*GW^2*Lam*TphiB*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1^4*ghZ*GW^2*Lam*TphiB*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (16*I)*G1*ghA*GW^3*Lam*TphiB*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*G1^3*ghA*GW^3*Lam*TphiB*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (16*I)*G1^3*ghA*GW*Lam*TphiW*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (32*I)*G1^2*ghZ*GW^2*Lam*TphiW*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1^3*ghA*GW^3*Lam*TphiW*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*ghZ*GW^4*Lam*TphiW*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (32*I)*G1^2*ghZ*GW^4*Lam*TphiW*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*ghZ*GW^6*Lam*TphiW*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1^4*ghZ*GW^2*Lam*TphiWB*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1^3*ghA*GW^3*Lam*TphiWB*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (16*I)*G1^2*ghWp*GW^2*del[ghZbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*ghWp*GW^4*
   del[ghZbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (16*I)*G1^2*ghWp*GW^2*Lam*TphiB*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*G1^4*ghWp*GW^2*Lam*TphiB*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (32*I)*G1^2*ghWp*GW^2*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] - (16*I)*ghWp*GW^4*Lam*TphiW*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] + 
  (32*I)*G1^2*ghWp*GW^4*Lam*TphiW*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*ghWp*GW^6*Lam*TphiW*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1^3*ghWp*GW*Lam*TphiWB*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1^4*ghWp*GW^2*Lam*TphiWB*vev^2*
   del[ghZbar, Index[Lorentz, mu]]*Wbar[Index[Lorentz, mu]] - 
  (16*I)*G1*ghWp*GW^3*Lam*TphiWB*vev^2*del[ghZbar, Index[Lorentz, mu]]*
   Wbar[Index[Lorentz, mu]] + (16*I)*G1^2*ghWm*GW^2*
   del[ghWmbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] + 
  (16*I)*ghWm*GW^4*del[ghWmbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] + 
  (16*I)*G1^2*ghWm*GW^2*Lam*TphiB*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] - (16*I)*G1^4*ghWm*GW^2*Lam*TphiB*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] - 
  (32*I)*G1^2*ghWm*GW^2*Lam*TphiW*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] - (16*I)*ghWm*GW^4*Lam*TphiW*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] + 
  (32*I)*G1^2*ghWm*GW^4*Lam*TphiW*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] + (16*I)*ghWm*GW^6*Lam*TphiW*vev^2*
   del[ghWmbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] + 
  (16*I)*G1^4*ghWm*GW^2*Lam*TphiWB*vev^2*del[ghWmbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] - (16*I)*G1^2*ghWp*GW^2*
   del[ghWpbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] - 
  (16*I)*ghWp*GW^4*del[ghWpbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] - 
  (16*I)*G1^2*ghWp*GW^2*Lam*TphiB*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] + (16*I)*G1^4*ghWp*GW^2*Lam*TphiB*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] + 
  (32*I)*G1^2*ghWp*GW^2*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] + (16*I)*ghWp*GW^4*Lam*TphiW*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] - 
  (32*I)*G1^2*ghWp*GW^4*Lam*TphiW*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]] - (16*I)*ghWp*GW^6*Lam*TphiW*vev^2*
   del[ghWpbar, Index[Lorentz, mu]]*Z[Index[Lorentz, mu]] - 
  (16*I)*G1^4*ghWp*GW^2*Lam*TphiWB*vev^2*del[ghWpbar, Index[Lorentz, mu]]*
   Z[Index[Lorentz, mu]])/(16*(G1^2 + GW^2)^(3/2))


